### ISSUE TITLE
Budgie crashes on login

### ISSUE THREAD

**Issue by Tebro** [budgie-desktop/budgie-desktop#661] opened 2016-10-19 14:06 UTC
**Operating System**: e.g. Solus 1.2.1
**Budgie version**: i.e. Budgie 10.2.8

**The issue encountered**
When login in after a boot it starts to load up budgie, but then crashes and returns to login screen.

Journalctl reports these lines:

```
Oct 19 16:47:22 boomer budgie-wm.desktop[1259]: (budgie-wm:1259): GLib-GObject-WARNING **: invalid (NULL) pointer instance
Oct 19 16:47:22 boomer budgie-wm.desktop[1259]: (budgie-wm:1259): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 19 16:47:22 boomer budgie-wm.desktop[1259]: current session already has an ibus-daemon.

```

**Steps to reproduce the issue**
Unknown

**Comment by ikeydoherty** [comment] 2016-10-19 17:49
How is ibus-daemon already starting before you get to the window manager? Any custom autostart stuff?

**Comment by Tebro** [comment] 2016-10-19 18:36
No, nothing custom.

**Comment by ikeydoherty** [comment] 2016-10-19 19:15
On my install:

```
Oct 19 20:01:03 solus-bdw gnome-settings-daemon.desktop[1131]: ** (gnome-settings-daemon:1131): WARNING **: Schemas 'org.gnome.desktop.a11y' has not been setup
Oct 19 20:01:03 solus-bdw budgie-wm.desktop[1195]: (budgie-wm:1195): GLib-GObject-WARNING **: invalid (NULL) pointer instance
Oct 19 20:01:03 solus-bdw budgie-wm.desktop[1195]: (budgie-wm:1195): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 19 20:01:04 solus-bdw budgie-panel.desktop[1218]: ** Message: IconTasklistApplet.vala:404: Invalid application! os-installer.desktop
Oct 19 20:01:04 solus-bdw gnome-session[1064]: gnome-session-binary[1064]: WARNING: Failed to start app: Unable to start application: Text was empty (or contained only whitespace)
Oct 19 20:01:04 solus-bdw gnome-session-binary[1064]: WARNING: Failed to start app: Unable to start application: Text was empty (or contained only whitespace)
Oct 19 20:01:04 solus-bdw gnome-session-binary[1064]: Entering running state
```

Note how I have the same 2 errors from budgie-wm, but I don't have an issue with it already running..

**Comment by ikeydoherty** [comment] 2016-10-19 19:18
You on the stable or unstable repos btw?

**Comment by Tebro** [comment] 2016-10-19 19:28
Stable repos. I had no issue before, came home, installed the updates and rebooted.

**Comment by Tebro** [comment] 2016-10-19 19:37
`Oct 19 22:30:54 boomer kernel: budgie-wm[2295]: segfault at 38 ip 000000000040b210 sp 00007ffcfbb94870 error 4 in budgie-wm[400000+22000]
`

Found this detail in the log as well (adding here for the record)

**Comment by Tebro** [comment] 2016-10-20 06:41
```
Oct 20 09:36:34 boomer gnome-settings-daemon.desktop[5103]: ** (gnome-settings-daemon:5103): WARNING **: Schemas 'org.gnome.desktop.a11y' has not been setup
Oct 20 09:36:34 boomer budgie-wm.desktop[5122]: (budgie-wm:5122): GLib-GObject-WARNING **: invalid (NULL) pointer instance
Oct 20 09:36:34 boomer budgie-wm.desktop[5122]: (budgie-wm:5122): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: WARNING: Application 'budgie-wm.desktop' killed by signal 11
Oct 20 09:36:35 boomer gnome-session-binary[5037]: WARNING: Application 'budgie-wm.desktop' killed by signal 11
Oct 20 09:36:35 boomer gnome-settings-daemon.desktop[5103]: (gnome-settings-daemon:5103): wacom-plugin-WARNING **: Failed to create GnomeRRScreen: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.9 was not provided by any .service files
Oct 20 09:36:35 boomer gnome-settings-daemon.desktop[5103]: (gnome-settings-daemon:5103): color-plugin-WARNING **: failed to get screens: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.9 was not provided by any .service files
Oct 20 09:36:35 boomer gnome-settings-daemon.desktop[5103]: (gnome-settings-daemon:5103): common-plugin-WARNING **: Failed to construct RR screen: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.9 was not provided by any .service files
Oct 20 09:36:35 boomer budgie-wm.desktop[5166]: (budgie-wm:5166): GLib-GObject-WARNING **: invalid (NULL) pointer instance
Oct 20 09:36:35 boomer budgie-wm.desktop[5166]: (budgie-wm:5166): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: Entering running state
Oct 20 09:36:35 boomer gnome-settings-daemon.desktop[5103]: (gnome-settings-daemon:5103): media-keys-plugin-WARNING **: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.15 was not provided by any .service files (2)
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: WARNING: Application 'budgie-wm.desktop' killed by signal 11
Oct 20 09:36:35 boomer gnome-session-binary[5037]: WARNING: Application 'budgie-wm.desktop' killed by signal 11
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: WARNING: App 'budgie-wm.desktop' respawning too quickly
Oct 20 09:36:35 boomer gnome-session-binary[5037]: WARNING: App 'budgie-wm.desktop' respawning too quickly
Oct 20 09:36:35 boomer gnome-session-binary[5037]: Unrecoverable failure in required component budgie-wm.desktop
Oct 20 09:36:35 boomer gnome-session[5037]: ** (gnome-session-failed:5196): WARNING **: Cannot open display:
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session[5037]: gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer gnome-session-binary[5037]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 20 09:36:35 boomer budgie-polkit.desktop[5168]: (budgie-polkit-dialog:5168): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer
Oct 20 09:36:35 boomer budgie-polkit.desktop[5168]: (budgie-polkit-dialog:5168): GLib-GObject-CRITICAL **: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 20 09:36:35 boomer org.gtk.vfs.Daemon[5066]: A connection to the bus can't be made
Oct 20 09:36:35 boomer budgie-desktop-nm-applet.desktop[5186]: (nm-applet:5186): nm-applet-WARNING **: Failed to initialize D-Bus: Failed to connect to socket /tmp/dbus-zvpvsyRODx: Connection refused
Oct 20 09:36:35 boomer gnome-settings-daemon.desktop[5103]: (gnome-settings-daemon:5103): Gdk-WARNING **: gnome-settings-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
Oct 20 09:36:35 boomer budgie-desktop-screensaver.desktop[5191]: (gnome-screensaver:5191): GLib-GIO-CRITICAL **: Error while sending AddMatch() message: The connection is closed
Oct 20 09:36:35 boomer budgie-desktop-screensaver.desktop[5191]: (gnome-screensaver:5191): GLib-GIO-CRITICAL **: Error while sending AddMatch() message: The connection is closed
Oct 20 09:36:35 boomer budgie-desktop-screensaver.desktop[5191]: (gnome-screensaver:5191): GLib-GIO-CRITICAL **: Error while sending AddMatch() message: The connection is closed
Oct 20 09:36:35 boomer budgie-desktop-screensaver.desktop[5191]: (gnome-screensaver:5191): Gdk-WARNING **: gnome-screensaver: Fatal IO error 111 (Connection refused) on X server :0.
Oct 20 09:36:35 boomer libcanberra-login-sound.desktop[5189]: (canberra-gtk-play:5189): Gdk-WARNING **: canberra-gtk-play: Fatal IO error 0 (Success) on X server :0.
Oct 20 09:36:36 boomer print-applet.desktop[5184]: /usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
Oct 20 09:36:36 boomer print-applet.desktop[5184]: from gi.repository import Notify
Oct 20 09:36:36 boomer print-applet.desktop[5184]: system-config-printer-applet: failed to connect to session D-Bus
Oct 20 09:36:36 boomer dropbox.desktop[5188]: Starting Dropbox...Dropbox isn't running!
Oct 20 09:36:36 boomer dropbox.desktop[5188]: Done!
Oct 20 09:36:37 boomer evolution-alarm-notify.desktop[5187]: (evolution-alarm-notify:5187): Gtk-WARNING **: cannot open display: :0
Oct 20 09:36:42 boomer systemd-coredump[5160]: Process 5122 (budgie-wm) of user 1000 dumped core.
Oct 20 09:36:42 boomer systemd-coredump[5183]: Process 5166 (budgie-wm) of user 1000 dumped core.
```

**Comment by ikeydoherty** [comment] 2016-10-20 07:00
Yeah this isn't a Budgie issue.

```
Oct 20 09:36:35 boomer org.gtk.vfs.Daemon[5066]: A connection to the bus can't be made

Oct 20 09:36:35 boomer budgie-desktop-nm-applet.desktop[5186]: (nm-applet:5186): nm-applet-WARNING **: Failed to initialize D-Bus: Failed to connect to socket /tmp/dbus-zvpvsyRODx: Connection refused

```

D-Bus is broken on your system.

**Comment by toudi** [comment] 2016-10-23 17:02
I am also experiencing this problem, exactly like Tebro (Solus 1.2.1, applied the updates and this is the result). After the bug gets fixed, can I somehow recover to console to download the updates? I tried Ctrl+Alt+F2, but the only thing which happened was that the mouse cursor dissapeared, but the console didn't appeared, the wallpaper stayed on). Or is the only way to reinstall the system?

**Comment by ikeydoherty** [comment] 2016-10-23 21:01
> After the bug gets fixed

As I've said this isn't a Budgie issue, the thing to do is to find out what commonality you have between what you've done on your systems that would cause d-bus to be broken. Does `/var/run/dbus/socket` exist?

**Comment by toudi** [comment] 2016-10-23 21:37
hmm but how can I find out whether it exist? Currently the only way for me to even log in is to select 'rescue / recovery' entry in GRUB. And I presume that I should check for existance of /var/run/dbus on the 'regular' Solus start. That's why I was trying to switch to terminal (Ctrl+Alt+F2) in order to run some commands, but I'm unable to do it (the cursor disappears and the wallpaper stays on)

**Comment by Tebro** [comment] 2016-10-24 10:58
I checked for the dbus socket, this is the file I have: `/var/run/dbus/system_bus_socket`, which is the file defined in /usr/lib/systemd/system/dbus.socket

**Comment by toudi** [comment] 2016-10-27 10:53
I had to use computer in meantime so I just reinstalled Solus 1.2.0.5 from scratch (just the ISO I had), now I did the system upgrade and the issue is on again which would suggest that it is not a random error. 

the packages that I have installed on the running 1.2.0.5 system were virtualenv, virtualenvwrapper, git

If you want me to shut up because this ain't helping anything feel free to tell me :D

**Comment by Tebro** [comment] 2016-10-27 12:02
I believe it to be helpful. The more info the easier to debug.

**Comment by JoshStrobl** [comment] 2017-02-28 22:01
Resolving as this is not a Budgie issue.

**Closed by JoshStrobl** 2017-02-28 22:01 UTC

**Comment by Citizen839X** [comment] 2025-02-15 12:11
> Resolving as this is not a Budgie issue.

BS huge as hell. Budgie sucks, as a matter of fact. The devs have their belly full from their actual career. No motivations to make it better, you know.

**Comment by Citizen839X** [comment] 2025-02-15 12:36
However, same problem here since the latest update. It's not Solus repo, it's the one from openSUSE. Same issues but I have a better backup solution like XFCE, always reliable. D-bus in my case isn't the issue, just for the chronicles. I suggest you, if I may, to change distro. Check openSUSE, they have a great installer where you can choose multiple desktop environments. Remember: just always provide yourself with a DM stable, a backup from more unstable ones, like Budgie.
