### ISSUE TITLE
Ability to click on notifications in Raven [Feature Request]

### ISSUE THREAD

**Issue by JonnyCodewalker** [budgie-desktop/budgie-desktop#1353] opened 2018-03-11 11:55 UTC
**Operating System**: Solus 3.99
**Budgie version**: Budgie 10.4

**The issue encountered**
Not able to click on notifications in Raven to "activate" them.
 ...

**Steps to reproduce the issue**
Use something that triggers a notification
Try to click on it.

**Comment by JoshStrobl** [comment] 2018-03-13 14:09
Duplicate of #260

**Closed by JoshStrobl** 2018-03-13 14:09 UTC
