### ISSUE TITLE
Budgie Panel Visual Bug

### ISSUE THREAD

**Issue by chifreagle** [budgie-desktop/budgie-desktop#824] opened 2017-03-12 21:36 UTC
**Operating System**: Solus 2017.01.01
**Budgie version**: Budgie 10.2.9

**The issue encountered*
The panel changes location as seen in this [video](https://www.youtube.com/watch?v=KbJ8ZNG3OI4)

**Steps to reproduce the issue**
As seen in the video : 
1. Open Raven Panel
2. Click on the log out button
3. Chose `cancel`
4. Click on the user indicator ~the power button icon in the Budgie Panel~
5. Chose `Cancel`

> The issue should be visible

**Comment by chifreagle** [comment] 2017-03-12 21:46
if anyone reproduced this issue and was unable to fix the panel you could follow those steps: 
> super + r (open raven)
2. Set Panel to top

Method 2 : 
from the terminal run : 
budgie-panel --replace

**Comment by fossfreedom** [comment] 2017-03-13 09:37
I cannot reproduce this under Ubuntu Budgie 17.04 :(

It may be related to this though - https://github.com/budgie-desktop/budgie-desktop/issues/726 - you've managed to crash the bottom panel using a different key and mouse click combination.

**Comment by david1603** [comment] 2017-03-16 10:47
I can't reproduce this under Arch either :( It looks like your step 4 should be followed by clicking on the shut down button, going by what happens in the video

**Comment by ikeydoherty** [comment] 2017-06-25 01:32
Fixed in git master by replacing `GtkPopover` with the new `BudgiePopover`. Will feature in the next release

**Closed by ikeydoherty** 2017-06-25 01:32 UTC
