### ISSUE TITLE
budgie-run-dialog doesn't run some apps from the first time

### ISSUE THREAD

**Issue by nazar-pc** [budgie-desktop/budgie-desktop#717] opened 2016-11-08 16:36 UTC
**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.2.8

**The issue encountered**
There are some apps that do not run from the first call and require exactly 2 calls with 100% reproducibility. 2 of such apps are: `gnome-disks` and `dconf-editor`. However, other apps like `clementine`, `ghetto-skype`, `ccsm` and many others in 100% of cases run from the first call.

**Steps to reproduce the issue**
* run `budgie-run-dialog`
* type `dconf` (dconf-editor gets selected)
* press Enter

**Observed behavior**
Nothing, if I repeat the same second time it works. Third time - doesn't, fourth time - works again and so forth.

Nothing is shown in terminal, exit status code is always `0`.

**Expected behavior**
Any app should run from the first call.

#### Clementine's desktop file (`/usr/share/applications/clementine.desktop`):
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Clementine
Name[sr]=Клементина
Name[sr@ijekavian]=Клементина
Name[sr@ijekavianlatin]=Klementina
Name[sr@latin]=Klementina
GenericName=Clementine Music Player
GenericName[ca]=Reproductor de música Clementine
GenericName[es]=Reproductor de música Clementine
GenericName[pl]=Odtwarzacz muzyki Clementine
GenericName[pt]=Reprodutor de músicas Clementine
GenericName[sl]=Predvajalnik glasbe Clementine
GenericName[sr]=Клементина музички плејер
GenericName[sr@ijekavian]=Клементина музички плејер
GenericName[sr@ijekavianlatin]=Klementina muzički plejer
GenericName[sr@latin]=Klementina muzički plejer
Comment=Plays music and last.fm streams
Comment[ca]=Reproducció de música i fluxos de Last.fm
Comment[es]=Reproducción de música y flujos de Last.fm
Comment[pl]=Odtwarzanie muzyki i strumieni last.fm
Comment[pt]=Reprodução de músicas e emissões last.fm
Comment[sl]=Predvaja glasbo in pretoke last.fm
Comment[sr]=Репродукује музику и last.fm токове
Comment[sr@ijekavian]=Репродукује музику и last.fm токове
Comment[sr@ijekavianlatin]=Reprodukuje muziku i last.fm tokove
Comment[sr@latin]=Reprodukuje muziku i last.fm tokove
Exec=clementine %U
TryExec=clementine
Icon=clementine
Terminal=false
Categories=AudioVideo;Player;Qt;Audio;
StartupNotify=false
MimeType=application/ogg;application/x-ogg;application/x-ogm-audio;audio/aac;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/vnd.rn-realaudio;audio/vorbis;audio/x-flac;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-ms-wma;audio/x-musepack;audio/x-oggflac;audio/x-pn-realaudio;audio/x-scpls;audio/x-speex;audio/x-vorbis;audio/x-vorbis+ogg;audio/x-wav;video/x-ms-asf;x-content/audio-player;x-scheme-handler/zune;x-scheme-handler/itpc;x-scheme-handler/itms;x-scheme-handler/feed;
Actions=Play;Pause;Stop;StopAfterCurrent;Previous;Next;

[Desktop Action Play]
Name=Play
Exec=clementine --play
Name[af]=Speel
Name[be]=Прайграць
Name[bg]=Възпроизвеждане
Name[br]=Lenn
Name[ca]=Reprodueix
Name[cs]=Přehrát
Name[da]=Afspil
Name[de]=Wiedergabe
Name[el]=Αναπαραγωγή
Name[es]=Reproducir
Name[et]=Mängi
Name[eu]=Erreproduzitu
Name[fa]=پخش
Name[fi]=Toista
Name[fr]=Lecture
Name[ga]=Seinn
Name[gl]=Reproducir
Name[he]=נגינה
Name[hr]=Pokreni reprodukciju
Name[hu]=Lejátszás
Name[it]=Riproduci
Name[ja]=再生
Name[kk]=Ойнату
Name[lt]=Groti
Name[lv]=Atskaņot
Name[ms]=Mainkan
Name[nb]=Spill
Name[nl]=Afspelen
Name[oc]=Lectura
Name[pl]=Odtwarzaj
Name[pt]=Reproduzir
Name[pt_BR]=Reproduzir
Name[ro]=Redă
Name[ru]=Воспроизвести
Name[sk]=Hrať
Name[sl]=Predvajaj
Name[sr]=Пусти
Name[sr@ijekavian]=Пусти
Name[sr@ijekavianlatin]=Pusti
Name[sr@latin]=Pusti
Name[sv]=Spela upp
Name[tr]=Çal
Name[uk]=Відтворити
Name[vi]=Phát
Name[zh_CN]=播放
Name[zh_TW]=播放

[Desktop Action Pause]
Name=Pause
Exec=clementine --pause
Name[be]=Прыпыніць
Name[bg]=Пауза
Name[br]=Ehan
Name[ca]=Pausa
Name[cs]=Pozastavit
Name[el]=Παύση
Name[es]=Pausar
Name[et]=Paus
Name[eu]=Pausarazi
Name[fa]=ایست
Name[fi]=Keskeytä
Name[ga]=Cuir ar sos
Name[gl]=Pausa
Name[he]=השהייה
Name[hr]=Pauza
Name[hu]=Szünet
Name[it]=Pausa
Name[ja]=一時停止
Name[kk]=Аялдату
Name[ko]=일시중지
Name[lt]=Pristabdyti
Name[lv]=Pauze
Name[nl]=Pauze
Name[oc]=Pausa
Name[pl]=Pauza
Name[pt]=Pausa
Name[pt_BR]=Pausar
Name[ro]=Pauză
Name[ru]=Приостановить
Name[sk]=Pozastaviť
Name[sl]=Začasno ustavi
Name[sr]=Паузирај
Name[sr@ijekavian]=Паузирај
Name[sr@ijekavianlatin]=Pauziraj
Name[sr@latin]=Pauziraj
Name[sv]=Gör paus
Name[tr]=Duraklat
Name[uk]=Призупинити
Name[vi]=Tạm dừng
Name[zh_CN]=暂停
Name[zh_TW]=暫停

[Desktop Action Stop]
Name=Stop
Exec=clementine --stop
Name[be]=Спыніць
Name[bg]=Спиране
Name[br]=Paouez
Name[ca]=Atura
Name[cs]=Zastavit
Name[de]=Anhalten
Name[el]=Σταμάτημα
Name[es]=Detener
Name[et]=Peata
Name[eu]=Gelditu
Name[fa]=ایست
Name[fi]=Pysäytä
Name[ga]=Stad
Name[gl]=Deter
Name[he]=הפסקה
Name[hr]=Zaustavi reprodukciju
Name[hu]=Leállít
Name[it]=Ferma
Name[ja]=停止
Name[kk]=Тоқтату
Name[ko]=중지
Name[lt]=Stabdyti
Name[lv]=Apturēt
Name[ms]=Henti
Name[nb]=Stopp
Name[nl]=Stoppen
Name[oc]=Arrestar
Name[pl]=Zatrzymaj
Name[pt]=Parar
Name[pt_BR]=Parar
Name[ro]=Oprește
Name[ru]=Остановить
Name[sk]=Zastaviť
Name[sl]=Zaustavi
Name[sr]=Заустави
Name[sr@ijekavian]=Заустави
Name[sr@ijekavianlatin]=Zaustavi
Name[sr@latin]=Zaustavi
Name[sv]=Stoppa
Name[tr]=Durdur
Name[uk]=Зупинити
Name[vi]=Dừng
Name[zh_CN]=停止
Name[zh_TW]=停止

[Desktop Action StopAfterCurrent]
Name=Stop after this track
Exec=clementine --stop-after-current
Name[be]=Спыніць пасьля гэтага трэку
Name[bg]=Спри след тази песен
Name[br]=Paouez goude ar roud-mañ
Name[ca]=Atura després d’aquesta peça
Name[cs]=Zastavit po této skladbě
Name[da]=Stop efter dette spor
Name[de]=Wiedergabe nach diesem Titel anhalten
Name[el]=Σταμάτημα μετά από αυτό το κομμάτι
Name[es]=Detener reproducción al finalizar la pista
Name[eu]=Gelditu pista honen ondoren
Name[fa]=ایست پس از این آهنگ
Name[fi]=Pysäytä toistettavan kappaleen jälkeen
Name[fr]=Arrêter la lecture après cette piste
Name[ga]=Stad i ndiaidh an rian seo
Name[gl]=Deter a reprodución despois da pista actual
Name[he]=הפסקה אחרי רצועה זו
Name[hr]=Zaustavi reprodukciju nakon ove pjesme
Name[hu]=Leállítás az aktuális szám után
Name[it]=Ferma dopo questa traccia
Name[ja]=このトラック後に停止
Name[ko]=이번 트랙 이후 정지
Name[lt]=Sustabdyti po šio takelio
Name[lv]=Apturēt pēc šīs dziesmas
Name[ms]=Henti selepas trek ini
Name[nb]=Stopp etter denne sangen
Name[nl]=Na dit nummer stoppen
Name[pl]=Zatrzymaj po tym utworze
Name[pt]=Parar após esta faixa
Name[pt_BR]=Parar depois desta música
Name[ro]=Oprește după această piesă
Name[ru]=Остановить после этого трека
Name[sk]=Zastaviť po tejto skladbe
Name[sl]=Zaustavi po tej skladbi
Name[sr]=Заустави после ове нумере
Name[sr@ijekavian]=
Name[sr@ijekavianlatin]=
Name[sr@latin]=Zaustavi posle ove numere
Name[sv]=Stoppa efter detta spår
Name[tr]=Bu parçadan sonra durdur
Name[uk]=Зупинити після цієї доріжки
Name[vi]=Dừng sau khi phát xong bài này
Name[zh_CN]=在此曲目后停止
Name[zh_TW]=在這首歌之後停止

[Desktop Action Previous]
Name=Previous
Exec=clementine --previous
Name[af]=Vorige
Name[be]=Папярэдні
Name[bg]=Предишна
Name[br]=A-raok
Name[ca]=Anterior
Name[cs]=Předchozí
Name[da]=Forrige
Name[de]=Vorheriger
Name[el]=Προηγούμενο
Name[es]=Anterior
Name[eu]=Aurrekoa
Name[fa]=پیشین
Name[fi]=Edellinen
Name[fr]=Précédent
Name[ga]=Roimhe
Name[gl]=Anterior
Name[he]=הקודם
Name[hr]=Prijašnje
Name[hu]=Előző
Name[it]=Precedente
Name[ja]=前へ
Name[lt]=Atgal
Name[lv]=Iepriekšējais
Name[nb]=Forrige
Name[nl]=Vorige
Name[pl]=Wstecz
Name[pt]=Anterior
Name[pt_BR]=Anterior
Name[ro]=Precedenta
Name[ru]=Предыдущий
Name[sk]=Predchádzajúca
Name[sl]=Predhodni
Name[sr]=Претходна
Name[sr@ijekavian]=Претходна
Name[sr@ijekavianlatin]=Prethodna
Name[sr@latin]=Prethodna
Name[sv]=Föregående
Name[tr]=Önceki
Name[uk]=Попередня
Name[uz]=Oldingi
Name[vi]=Trước
Name[zh_CN]=上一首
Name[zh_TW]=往前

[Desktop Action Next]
Name=Next
Exec=clementine --next
Name[af]=Volgende
Name[be]=Далей
Name[bg]=Следваща
Name[br]=Da-heul
Name[ca]=Següent
Name[cs]=Další
Name[da]=Næste
Name[de]=Weiter
Name[el]=Επόμενο
Name[es]=Siguiente
Name[eu]=Hurrengoa
Name[fa]=پسین
Name[fi]=Seuraava
Name[fr]=Suivant
Name[ga]=Ar aghaidh
Name[gl]=Próximo
Name[he]=הבא
Name[hr]=Sljedeće
Name[hu]=Következő
Name[id]=Berikut
Name[it]=Successivo
Name[ja]=次へ
Name[ko]=다음
Name[lt]=Toliau
Name[lv]=Uz priekšu
Name[ms]=Seterusnya
Name[nb]=Neste
Name[nl]=Volgende
Name[pl]=Dalej
Name[pt]=Seguinte
Name[pt_BR]=Próximo
Name[ro]=Următoarea
Name[ru]=Дальше
Name[sk]=Ďalšia
Name[sl]=Naslednji
Name[sr]=Следећа
Name[sr@ijekavian]=Сљедећа
Name[sr@ijekavianlatin]=Sljedeća
Name[sr@latin]=Sledeća
Name[sv]=Nästa
Name[tr]=İleri
Name[uk]=Наступна
Name[uz]=Keyingi
Name[vi]=Tiếp theo
Name[zh_CN]=下一首
Name[zh_TW]=下一個
```

#### Dconf-editor's desktop file (`/usr/share/applications/ca.desrt.dconf-editor.desktop`):
```
[Desktop Entry]
Name=dconf Editor
GenericName=Configuration editor for dconf
Comment=Directly edit your entire configuration database
Keywords=settings;configuration;
Exec=dconf-editor
Terminal=false
Type=Application
Icon=dconf-editor
StartupNotify=true
Categories=GNOME;GTK;System;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=dconf
X-GNOME-Bugzilla-Component=editor
X-GNOME-Bugzilla-Version=3.22.1
DBusActivatable=true
X-Ubuntu-Gettext-Domain=dconf
```

**Comment by ikeydoherty** [comment] 2016-11-08 16:47
Dupe of #658

**Closed by ikeydoherty** 2016-11-08 16:47 UTC
