### ISSUE TITLE
The panel disappears when opening while Raven is open

### ISSUE THREAD

**Issue by MatthewScholefield** [budgie-desktop/budgie-desktop#543] opened 2016-08-16 17:32 UTC
(Note: this has been moved from Phabricator)

I can't tell if this has been fixed already but in case it's not: Consistently whenever I hit super while raven is open budgie-panel disappears but the process doesn't return and continues to spew out the normal GTK errors.;

**Comment by nlaplante** [comment] 2016-08-17 10:18
Same here. I have to run `budgie-panel --replace` to get it back

**Comment by GladOSkar** [comment] 2016-09-13 21:42
Same Here. Only happens when in "Applications"-Tab, not in "Notifications"-Tab

**Comment by JoshStrobl** [comment] 2017-03-01 00:03
Not able to reproduce. Please validate against latest version of Budgie.

**Comment by MatthewScholefield** [comment] 2017-03-01 01:42
@JoshStrobl I just checked with the latest official version (10.2.9) and still encounter the issue, although no longer always on the first click, often the third or so. I'll test on the git branch once I get meson working.

**Comment by fossfreedom** [comment] 2017-03-01 07:20
@MatthewScholefield is this when the panel at the top or the bottom?

**Comment by chifreeagle** [comment] 2017-03-01 09:08
**Steps to reproduce**
1. You should have the panel set to bottom
2. Press `Super + N `
3. Press the Raven setting icon
4. Press super
> the panel should disappear

**another way of reproducing the problem**
1. You should have the panel at the bottom
2. Press `Super + N`
3. Enter Raven Settings 
4. Chose Panel
5. Select the size and replace it with some thing else ( do not use the + and -, replace directly)
> the panel should disappear

> changing the size using the panel using the `-` button brings up this issue #812 and this one #312 

Hope this helped :sweat_smile:

**Comment by fossfreedom** [comment] 2017-03-01 09:22
k - this then looks very similar as as https://github.com/budgie-desktop/budgie-desktop/issues/726

**Comment by fossfreedom** [comment] 2017-03-04 10:07
marking this as a duplicate of #726

**Closed by fossfreedom** 2017-03-04 10:07 UTC
Labels: duplicate
