### ISSUE TITLE
Panel over full-screen videos

### ISSUE THREAD

**Issue by iachopolo** [budgie-desktop/budgie-desktop#699] opened 2016-10-30 22:33 UTC
**Operating System**: Manjaro
**Budgie version**: Budgie 10.2.8

**The issue encountered**
In full screen mode in YouTube, panel is over the video. Same thing happens with VLC
![captura de pantalla de 2016-10-30 19-29-14](https://cloud.githubusercontent.com/assets/16168428/19840585/e98b1b7a-9ed7-11e6-8dca-bdfb89299346.png)

**Steps to reproduce the issue**
-Open a YouTube Video
-Click full-screen mode

Cheers!!

**Comment by fossfreedom** [comment] 2016-10-30 22:35
Duplicate of #630

**Comment by iachopolo** [comment] 2016-10-30 22:37
Oh sorry, I missed it

**Closed** 2016-11-01 05:57 UTC
