### ISSUE TITLE
The Jetbrains-Toolbox icon causes the panel length to change

### ISSUE THREAD

**Issue by Hentioe** [budgie-desktop/budgie-desktop#1232] opened 2017-10-31 08:43 UTC
By Budgie 10.4 on Ubuntu 16.04, when running Jetbreins Toolbox:

![selection_130](https://user-images.githubusercontent.com/13946976/32214346-7bbe55b0-be59-11e7-90b9-f56bed5fb063.png)

This is the original length:

![selection_131](https://user-images.githubusercontent.com/13946976/32214384-9fa0df52-be59-11e7-8fb3-0da8ed88e861.png)

It looks like Jetbrains' icon is too big to cause problems, but there is no problem a few months ago.

Jetbrains Toolbox address: https://www.jetbrains.com/toolbox/

Also, this is my setting:

![selection_132](https://user-images.githubusercontent.com/13946976/32214577-4a77b02c-be5a-11e7-8e40-75753667c28f.png)

This problem bothers me for a long time and looks like a small problem and I hope it can be solved. What else need to be provided can reply me :)

**Comment by fossfreedom** [comment] 2017-10-31 09:13
There is an open bug report on the jetbrains issue tracker.  The problem is that they ship the icon file that is not 22x22px - it is probably something like 64x64 or 128x128.

Since this is not a budgie desktop issue I'll close this here. https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FALL-1734#u=1505484324757

**Closed by fossfreedom** 2017-10-31 09:13 UTC

**Comment by Hentioe** [comment] 2017-11-27 06:27
The good news is that the latest Jetbrains-Toolbox icon is OK.

![_158](https://user-images.githubusercontent.com/13946976/33253588-09e1d756-d37f-11e7-975e-067a719479ee.png)
