### ISSUE TITLE
Workspace Switcher Doesn't Indicate Current Workspace

### ISSUE THREAD

**Issue by SolarLune** [budgie-desktop/budgie-desktop#733] opened 2016-11-16 04:15 UTC
Hello. 

So the "problem" is that the workspace switcher doesn't indicate the active monitor, it just indicates the active window (which can be confusing when you are focused on a monitor that doesn't have a window on it). 

It'd be nice to have it display the active monitor somehow.

EDIT: A related suggestion would be to display the active workspace number on switch.

**Comment by JoshStrobl** [comment] 2017-02-28 21:30
Duplicate of #412

**Closed by JoshStrobl** 2017-02-28 21:30 UTC
