### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by axarix-0815** [budgie-desktop/budgie-desktop#1175] opened 2017-10-01 08:43 UTC
Operating System: Solus 3
Budgie version: Budgie 10.4

The problem has occurred while enlarging the application icons. Between the icons is very much black space. I do not like that. A lot of space is wasted. For the elderly I would find it nice, if one could change the size of the application icons independently of the bar.

Rainer

**Comment by MaxJonasG** [comment] 2017-10-01 21:58
Are you scaling the icons or the panel? I might be mistaken but I believe the icons don't scale at all, they come in standard sizes (16x16, 32x32, 48x48, 96x96, 128x128), whenever a bigger size fits (plus a margin of 5 px) that size will be taken, hence the icon size jumps for panels at the sizes of 37, 53,101,133. I agree that this leads to a lot of dead space inbetween though.

**Comment by axarix-0815** [comment] 2017-10-02 07:44
Is there a way to only change the size of the icons. Without changing the panel? I would pass a script.

**Comment by fasolens** [comment] 2017-10-19 10:56
Operating System: ubuntu-budgie
Budgie version: Budgie 10.4
jetbrains toolbox application put in the panel the biggest icon is available.
![screenshot from 2017-10-19 12-46-03](https://user-images.githubusercontent.com/398144/31767746-acfbcc7a-b4cc-11e7-8af6-83154bea4d6a.png)

**Comment by fossfreedom** [comment] 2017-10-19 11:11
@fasolens the jetbrains issue you have isnt anything to-do with this particular issue.

A bug should be raised with Jetbrains - they are not respecting the icon size limit of their appindicator icon - it should be 22px.

**Comment by codingboa** [comment] 2017-10-19 12:04
I see it is already reported there. https://youtrack.jetbrains.com/issue/ALL-1734#u=1505484324757

**Comment by JoshStrobl** [comment] 2017-10-22 15:37
Closing as duplicate of #701

**Closed by JoshStrobl** 2017-10-22 15:37 UTC

**Comment by chaos-prevails** [comment] 2019-01-23 14:09
Hello,
I have the same issue with 18.04 budgie, and wire (wire.com) and riseup.net VPN (see screenshot).

Both are applications which are normally open at all times (messenger + VPN client).

![ubuntu_budgie_taskbar](https://user-images.githubusercontent.com/17159225/51611942-b6ee5d00-1f20-11e9-81ae-2c28e47324b0.png)
