### ISSUE TITLE
Removing keyboard layout crushes budgie-wm

### ISSUE THREAD

**Issue by CarlosZaldivar** [budgie-desktop/budgie-desktop#741] opened 2016-11-26 15:02 UTC
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8

**The issue encountered**
Removing currently selected keyboard layout crushes budgie-wm (segmentation fault). budgie-wm can be restarted after adding back the deleted layout. The issue is probably related to [#740](https://github.com/budgie-desktop/budgie-desktop/issues/740)

**Steps to reproduce the issue**
1. Add new keyboard layout
2. Select the newly added keyboard layout
3. Delete it

**Comment by RDR8** [comment] 2017-02-05 18:27
I can confirm that resetting the keyboard layout "fixes" it. I used`gsettings set org.gnome.desktop.input-sources current 0` at a shell prompt, i.e, Ctrl-Alt-F2. This resets the keyboard layout to the default.

**Comment by ikeydoherty** [comment] 2017-02-28 20:36
Dupe of #740

**Closed by ikeydoherty** 2017-02-28 20:36 UTC
