### ISSUE TITLE
Workspace Switcher Applet leaves traces on the Panel

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#1064] opened 2017-07-24 00:44 UTC
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1-404-g128a50a

Workspace Switcher Applet leaves traces (vertical lines) on the Panel. 

![Alt Text](http://i.imgur.com/vDCixPj.gif)

**Comment by JoshStrobl** [comment] 2017-08-04 02:10
Closing as a duplicate of #997

**Closed by JoshStrobl** 2017-08-04 02:10 UTC
