### ISSUE TITLE
Meta key does not close budgie menu always

### ISSUE THREAD

**Issue by duics** [budgie-desktop/budgie-desktop#605] opened 2016-09-18 14:00 UTC
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

Pressing meta key when budgie menu is open causes it to reopen, but it would probably be convenient and less confusing if the meta key could also be used to close the menu.

**Comment by diazbastian** [comment] 2016-09-19 01:44
Testing this issue the following occurs (the panel disappeared):

![captura de pantalla de 2016-09-18 22-31-46](https://cloud.githubusercontent.com/assets/5126124/18620798/198e6718-7df0-11e6-9a44-5a346749b21b.png)

I noticed that the behavior is not consistent, because sometimes when you press a second time the `Super` key, the menu closes, but in others again reopened (insisting on the `Super` key, happens what you see in the image).

**Comment by ikeydoherty** [comment] 2016-09-19 10:04
Yeah get the same here

**Comment by duics** [comment] 2016-09-24 08:04
I installed budgie on my laptop and there it seems to work fine. It's apparently only on my desktop that when I press meta button with budgie open, it will reopen instantly (without actually closing)

**Comment by ikeydoherty** [comment] 2016-09-24 14:51
Weirder again its only *partly* reproducible :)

**Comment by Malmz** [comment] 2016-09-24 14:56
I get this issue too. If I tap the meta key quickly it closes the menu, but if I hold it it re-opens.

**Comment by jwaterhouse** [comment] 2016-12-15 02:35
Might be something to do with button press/release events.

I noticed on my Arch machine that without the menu open, if I press the Meta key the menu only shows once it's released. And then with the menu open, on pressing Meta again it will close the menu, but then it opens again on release.

**Comment by fossfreedom** [comment] 2018-01-25 14:17
Correct me if I'm wrong but this was resolved in budgie-desktop v10.4

**Closed by fossfreedom** 2018-01-25 14:17 UTC
