### ISSUE TITLE
Workspace switcher: disable add work space popup

### ISSUE THREAD

**Issue by gazny** [budgie-desktop/budgie-desktop#1017] opened 2017-07-07 22:21 UTC
Mousing over the applet can cause a lot of icons to move around. This decreases productivity. 

Features requests:
Add setting into raven to disable the add workspace popup.

**Comment by ikeydoherty** [comment] 2017-07-13 14:29
Assigning to workspace applet owner (@cybre)

**Comment by cybre** [comment] 2017-07-13 17:39
I plan to make it configurable and have it off by default.

**Comment by bja-au** [comment] 2017-07-21 01:55
In the mean time is there any way to revert to the previous version please?

**Comment by ikeydoherty** [comment] 2017-07-21 06:12
No - this is the applet we have now. The only reason I can see for things jumping around is invalid Budgie settings, i.e. using builtin-theme while using a theme that actually supports Budgie (like Adapta)

**Comment by bja-au** [comment] 2017-07-21 07:59
The moving around is caused by the addition of the + (add workspace) field which auto opens when ever you mouse over the applet - also the way the applet works has been changed so that when you click on a workspace which has >1 windows, it drops down a selection menu for you to select the window you want, this drop down window doesn't (in my case) disappear once you make a selection.
I would much prefer the original applet! I see above the applet creator is going to make (some of??) the changes configurable so hopefully he will have an option for the original applet :)

**Comment by ikeydoherty** [comment] 2017-07-21 08:00
The original applet did nothing else but include `Wnck.Pager` which completely bricked the panel in recent changes (it refuses to obey any size constraints, and would force the panel to take up the entire screen.)

**Comment by bja-au** [comment] 2017-07-21 08:10
bugger :(
oh well such is life!

**Comment by ikeydoherty** [comment] 2017-08-14 15:49
this was fixed in git

**Closed by ikeydoherty** 2017-08-14 15:49 UTC
