### ISSUE TITLE
icon-task-list applet on Panel

### ISSUE THREAD

**Issue by ChrisOfBristol** [budgie-desktop/budgie-desktop#1130] opened 2017-08-30 16:20 UTC
Bottom Panel - Application icons are small compared with the panel height, most applet icons are tiny.
![tiny](https://user-images.githubusercontent.com/20310498/29883031-d567d7f0-8da6-11e7-82dc-7f5a649b613f.png)

There are a few oddities with the icon-task-list applet:
	Clicking opens another instance instead of switching to open application.
	Clicking sometimes shows another icon instead of underlining pinned one.
	Doesn't show "Startup Applications", presumably because they were open before the panel was started.
	It's not possible to use the scrollwheel on an icon to switch between open windows of that application.
These are sort of basic - they all work in Plank.

**Operating System**: Ubuntu Budgie 17.04
**Budgie version**: i.e. Budgie 10.4

**Comment by JoshStrobl** [comment] 2017-10-22 15:58
Closing as duplicate of #701

**Closed by JoshStrobl** 2017-10-22 15:58 UTC
