### ISSUE TITLE
Make battery icon show finer levels

### ISSUE THREAD

**Issue by der-eismann** [budgie-desktop/budgie-desktop#797] opened 2017-02-10 21:49 UTC
**Operating System**: Solus 2017.01.01
**Budgie version**: Budgie 10.2.9

**The issue encountered**
In my opinion the battery icon in the status bar is pretty useless. I think it has 3 states - full, empty (<10%) and anything in between. I was often surprised that my battery is almost empty because the icon still showed about 50% - see attached image, battery status was ca. 11%.
![bildschirmfoto vom 2017-02-10 22-46-23](https://cloud.githubusercontent.com/assets/10406217/22845447/fc3fc3ae-efe2-11e6-828c-82af2843ced0.png)

Would it be possible to make the icon a bit finer or show the percentage next to the icon?

**Comment by ikeydoherty** [comment] 2017-02-13 09:21
The icons aren't ours. We can only be more granular when more icons exist to show more levels. Without them we can't really do anything.

**Comment by der-eismann** [comment] 2017-02-13 12:56
Thanks for your reply!
Where are the icons from, Gnome? Is there no way to create new icons or could this come with Budgie 11?

**Comment by ikeydoherty** [comment] 2017-02-13 13:22
They come from your icon theme. It's very possible to create new icons, but they won't be freedesktop compliant (new names). I'm not personally capable of making decent icons :)

**Comment by ideaman924** [comment] 2017-02-19 03:47
ikeydoherty, then would it be possible to configure budgie to let us show percentage and remaining time? Then we wouldn't have to rely on the battery icon. Thanks.

**Comment by simonsaysthis** [comment] 2017-02-26 14:02
I agree that the battery indicator needs to be relooked. A percentage would be a reasonable compromise. If you have a laptop with two internal batteries like me budgie will show two battery icons. Not a huge issue but an annoying aesthetic element.

**Comment by JoshStrobl** [comment] 2017-02-28 20:48
Duplicate of #691

**Closed by JoshStrobl** 2017-02-28 20:48 UTC
