### ISSUE TITLE
Adding <Super>C to clear all notifications

### ISSUE THREAD

**Issue by UnlawfulMonad** [budgie-desktop/budgie-desktop#1317] opened 2018-02-07 22:18 UTC
I've been trying to add a key binding (`<Super>C`) to call `NotificationsView.clear_all`. Currently I've hooked up the keybinding but I can't find a path between `BudgieWM` (where the keybinding is received) and `NotificationsView` which seems to only be accessible as a dbus interface (`org.freedesktop.Notifications`). There doesn't seem to be any way to do this from either `Raven` or `RavenIface`. Since there's no way to get a list of notification IDs I would propose having `NotificationsView` be a simple wrapper (to keep implementing `org.freedesktop.Notifications`) around a new class where this functionality is exposed as a new dbus interface with a `ClearAll` method.

Is this an okay way to go about this?

**Comment by JoshStrobl** [comment] 2018-02-08 23:05
Duplicate of #709

**Closed by JoshStrobl** 2018-02-08 23:05 UTC
Labels: duplicate
