### ISSUE TITLE
Bottom budgie-panel disappears after super button use

### ISSUE THREAD

**Issue by IraetyrrWaerrae** [budgie-desktop/budgie-desktop#726] opened 2016-11-14 01:16 UTC
Hi, my OS is Ubuntu Budgie Remix, i use really basic configuration, its my 2nd day with this OS.

For now if i change panel position to the bottom panel will dissapeard after few minutes (after few times use of super button).

It look same to [this](https://github.com/budgie-desktop/budgie-desktop/issues/316) issue, so i wont attach a screenshot.

Problem occurs only if panel is BOTTOM AND after login and super-button use OR if we have used raven and open panel by super-button. - i dont know why panel still alive after open menu by mouse.

[VIDEO](https://youtu.be/spstDYeQLUU)

**Comment by niyasc** [comment] 2016-11-14 08:45
Please include following details in your problem descriptions. That will make things easier for people who will be looking into this issue.

- Version of **budgie-remix**.
- Whether you have done all updates.

**Comment by IraetyrrWaerrae** [comment] 2016-11-14 19:52
Budgie Remix 16.04, updated yesterday

**Comment by cicerotully** [comment] 2016-11-18 15:03
I've had the same issue with my budgie panel, running atop Solus. I have a two panel set-up with my main panel at the bottom of the screen. Sometimes when I use the super-button, _this_ panel will disappear or move to the top. 

So far, I have been dealing with it by opening up Raven and moving the bottom panel to the top and then back to the bottom again. As the OP said, it doesn't behave like this every time I press the super-button, so it's not debilitating. 

I think this might be something related to issue #651 , which Ikey says can't be resolved until the re-write (next release?).

**Comment by fossfreedom** [comment] 2017-02-19 23:02
From a valgrind this part of the codebase is the issue:

panel.vala

```
    public override bool draw(Cairo.Context cr)
    {
        if (render_scale == 0.0) {
            return base.draw(cr);
        } else if (render_scale == 1.0) {
            return Gdk.EVENT_STOP;
}
```
The crash occurs when calling return base.draw(cr) (real_draw method in this picture) line 4651

![](http://pix.toile-libre.org/upload/original/1487544978.png)

![](http://pix.toile-libre.org/upload/original/1487545247.png)

for whatever reason the cairocontext can be invalid at this point - dunno though what sort of checks need to be done to check the contents of the context is valid.

**Comment by david1603** [comment] 2017-03-16 11:01
This is also present on Arch, updated today. I can reproduce it easily by moving the panel to the bottom and mashing the super key ~20 times. Leaving the panel at the top doesn't break anything though

**Comment by enoch85** [comment] 2017-04-17 00:21
I can reproduce this on latest 17.04 with the panel on the bottom. Any ETA for a fix on this?

**Comment by ikeydoherty** [comment] 2017-04-17 00:23
Budgie 11

**Comment by enoch85** [comment] 2017-04-17 01:19
@ikeydoherty Thanks! Just installed Budgie and have no clue about release chedules and stuff like that, so is it in a week, a month or a day?

Also, don't know if it's related, but just an hour ago I got this:
![screenshot from 2017-04-17 03-17-05](https://cloud.githubusercontent.com/assets/4511254/25075897/7a8622aa-231c-11e7-9532-3677e32445c7.png)

No icons, whatsoever, and if I try to reach my files on the Desktop through Files it just force closes Files. Only way I can access my files on the Desktop is trough CLI. I hope that gets fixed soon. :)

**Comment by ikeydoherty** [comment] 2017-04-17 01:22
Files isn't a part of Budgie - I think you just haven't installed the complete set of packages (GSD/GNOME bits)

**Comment by ikeydoherty** [comment] 2017-04-17 01:32
Budgie 11 hasn't started yet btw, 10.3 was blocking it. ATM I have a lot on my plate with the solus snapshot but once thats done (and solus infra done) I can get back to doing more Budgie :)

**Comment by enoch85** [comment] 2017-04-17 10:39
@ikeydoherty Ok I totally understand. 

Just wanted to check one thing though; this statement isn't correct?

> You are always updated to the latest software, bug free and more stable.

Found here: https://ubuntubudgie.org/

**Comment by niyasc** [comment] 2017-04-17 10:56
@enoch85 How did you install budgie desktop? and in which operating system?

**Comment by fossfreedom** [comment] 2017-04-17 10:56
must have a word with our website administrator - "bug free" - highly unlikely!

**Comment by enoch85** [comment] 2017-04-17 11:00
@niyasc I downladed the 17.04 release from https://ubuntubudgie.org/, made a USB ISO with Rufus, installed it, and ended up here. :)

**Comment by niyasc** [comment] 2017-04-17 11:04
@enoch85 Did you customize it after installation? :confused: 

Default configurations are different from what you have shown on the screen.

I'm not sure whether desktop listing of files are enabled by default. Still, you should be able to access files on desktop through **File** (nautilus).

**Comment by enoch85** [comment] 2017-04-17 11:06
@niyasc While I was looking for a soulution to the panel issue I ran one command that could have caused this: `dbus-launch --exit-with-session gnome-session` Don't know it that one failed on me. :/

**Comment by fossfreedom** [comment] 2017-04-17 11:06
ok @enoch85 this is nothing to-do per-se with this particular issue nor on this upstream tracker - suggest pop into the ubuntu-budgie gitter chatroom and someone will help. https://gitter.im/ubuntubudgie/community

**Comment by enoch85** [comment] 2017-04-17 11:07
@fossfreedom I'm about do re-install 16.04.2 instead. I need to be on 4.8 kernel (max) anyway. Thanks for your help!

**Comment by Winterwolf** [comment] 2017-05-28 15:07
Same problem on 17.04. Panel disappears when I pressing super key and teleports from top to bottom all time.

**Comment by ikeydoherty** [comment] 2017-05-28 17:06
It's open because its not fixed.

**Comment by ikeydoherty** [comment] 2017-06-25 01:38
Fixed by replacing `GtkPopover` with our own `BudgiePopover` in git. This will be available in the next release.

**Closed by ikeydoherty** 2017-06-25 01:38 UTC
Labels: bug
