### ISSUE TITLE
Starting files with Launcher

### ISSUE THREAD

**Issue by nexus86** [budgie-desktop/budgie-desktop#580] opened 2016-09-12 09:50 UTC
So today i noticed that the launcher starts everything if you type the name and hit enter except files. I tried it in the latest Solus release 1.2.0. I know i can create a shortcut for launching the home folder.

**Comment by ikeydoherty** [comment] 2016-09-12 13:26
I just launched it now on my system. Locale issue.. ?

**Comment by feskyde** [comment] 2016-09-12 14:17
I think he means opening files and folders directly from the Budgie Menu, like in Cinnamon

**Comment by ikeydoherty** [comment] 2016-09-12 17:13
Oh. Damn you GNOME Files. lol.

@nexus86 please clarify what it is you're requesting or reporting as clearly I don't get it. :p

**Comment by nexus86** [comment] 2016-09-13 05:16
I made a small video to show you what i mean xD

[launcherBug.zip](https://github.com/solus-project/budgie-desktop/files/468936/launcherBug.zip)

**Comment by nexus86** [comment] 2016-09-13 05:23
I also noticed that files is opening after a few tries.

**Comment by GladOSkar** [comment] 2016-09-13 21:32
I reproduced it. For everyone who does not want to download the Video:

When using the "Run Dialog"

**Comment by ikeydoherty** [comment] 2016-10-18 04:14
Not downloading random zip from github sorry.. Please reverify when I push 10.2.8 out

**Comment by GladOSkar** [comment] 2016-10-19 10:23
Reverified. Still behaves the way i explained. 

> When using the "Run Dialog" Launcher, search for "files" and hit enter/click it it does not open the "Files" (nautilus) Application.

BUT after booting, if you start "files"/nautilus via Budgie-Menu once, it then also works via the "Run Dialog"-Launcher.

**Comment by ikeydoherty** [comment] 2017-04-16 20:06
Yeah turns out this was dbus activation stuff fixed in 10.2.9

**Closed by ikeydoherty** 2017-04-16 20:06 UTC
