### ISSUE TITLE
Budgie Applets Overlap with Each Other

### ISSUE THREAD

**Issue by moriel5** [budgie-desktop/budgie-desktop#855] opened 2017-04-16 13:16 UTC
I have verified this with the Icon Tasks List Applet:
When opening too many windows, the newer windows appear underneath the further applets on the panel (and at a certain point, are simply off the screen), are inaccessible. and some of them do not have window options (open new window, etc) on the right click menu on the window icon on the applet.

As I cannot upload files through ForkHub, I am inserting a link to the screenshot I had uploaded from my PC to Phabricator:

https://dev.solus-project.com/file/data/kq6z45xrjjs4mzdfbzzs/PHID-FILE-ugxiz55kusenoktdmaar/Screenshot_from_2017-04-16_11%3A07%3A26.png

I am (like usual) utilizing the unstable repo, and I had ensured that the system was up-to-date right before sending this in.

**Comment by ikeydoherty** [comment] 2017-04-16 14:32
This is a duplicate of #83

**Closed by ikeydoherty** 2017-04-16 14:32 UTC
