### ISSUE TITLE
Option to group notifications by app in order to prevent spam. [Feature Request]

### ISSUE THREAD

**Issue by JonnyCodewalker** [budgie-desktop/budgie-desktop#1352] opened 2018-03-11 11:54 UTC
**Operating System**: Solus 3.99
**Budgie version**: Budgie 10.4

**The issue encountered**
Notifications are not grouped by App, so ha ving a chat notifying you spams out every other notification.
 ...

**Steps to reproduce the issue**
Use web.whatsapp.com or similar.
Get someone to write you a bunch of messages.
Look at raven-notifications.

**Comment by JoshStrobl** [comment] 2018-03-13 14:10
Duplicate of #763

**Closed by JoshStrobl** 2018-03-13 14:10 UTC
