### ISSUE TITLE
Budgie Menu not showing applications installed during currunt session. 

### ISSUE THREAD

**Issue by Dark-Witcher** [budgie-desktop/budgie-desktop#761] opened 2016-12-26 17:44 UTC
**Operating System**: e.g. Budgie Remix (Ubuntu 16.10)
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**
After installing a new application I have to log out and log in again in order for it to show in the Budgie Menu. 
 ...

**Steps to reproduce the issue**

Install an application.
 ...

**Comment by fossfreedom** [comment] 2016-12-26 18:00
This is actually a duplicate of #632 ... Under debian and Ubuntu (mainly) the panel and session can crash.  We have had to stop the automatic men refresh capability because of this.  Cross fingers the new brisk menu in budgie v11 will resolve this.

**Comment by ikeydoherty** [comment] 2016-12-27 06:44
Closing as non vanilla dupe

**Closed by ikeydoherty** 2016-12-27 06:44 UTC
