### ISSUE TITLE
tasklist pushs out other icons once the space is not enough for all window titles

### ISSUE THREAD

**Issue by braindumped** [budgie-desktop/budgie-desktop#1138] opened 2017-09-05 07:26 UTC
**Operating System**: Ubuntu Budgie
**Budgie version**: budgie-core 10.4-0ubuntu0.1
**The issue encountered**
I'm running ubuntubudgie since April or so and am quite happy with the budgie desktop. I've configured to have a tasklist in the top panel (left aligned) and icons like clock, user indicator etc on the top right.
When I had too many windows open the list of accessible windows got limited by my screen width and if there where too many the list scrolled out under the icons to the right.
this behaviour changed recently that all my icons get pushed out the screen. Screenshots attached.

![too little space](https://user-images.githubusercontent.com/710556/30049551-69851f9c-921b-11e7-99e2-d97b4e753b13.png)
![enough space after closing a window](https://user-images.githubusercontent.com/710556/30049562-7470a7c8-921b-11e7-9b4a-62a177b86db4.png)
![my config](https://user-images.githubusercontent.com/710556/30049752-1eab35b4-921c-11e7-9b11-d08518295569.png)

**Comment by ikeydoherty** [comment] 2017-09-05 15:13
Yeah this issue exists at least 5 times in the tracker. I'm a bit annoyed now that people won't look for a duplicate before reporting it - this tracker is now too hard to use. Don't get me wrong, I know the bug itself is also annoying, but the issue tracker should at least be usable.

**Comment by JoshStrobl** [comment] 2017-09-05 15:19
Duplicate of #83

**Closed by JoshStrobl** 2017-09-05 15:19 UTC
Labels: duplicate

**Comment by braindumped** [comment] 2017-09-05 18:24
sorry, I overlooked #83
