### ISSUE TITLE
Can’t take screenshots with keyboard shortcut 

### ISSUE THREAD

**Issue by gabrc52** [budgie-desktop/budgie-desktop#1162] opened 2017-09-17 17:56 UTC
**Operating System**: Solus 3/Manjaro
**Budgie version**: Budgie 0.4

**The issue encountered**

It’s currently not possible to take screenshots using the built-in keyboard shortcut in Gnome Settings.

**Steps to reproduce the issue**

Set a keyboard shortcut to take screenshots (they are set by default) using gnome-control-center.
Press it. 
Screenshot isn’t taken, as evidenced by the sound cue.

**Comment by fossfreedom** [comment] 2017-09-17 18:13
Duplicate of #261

**Closed by fossfreedom** 2017-09-17 18:13 UTC
