### ISSUE TITLE
There is no option to set notification position on budgie desktop.

### ISSUE THREAD

**Issue by veshi11** [budgie-desktop/budgie-desktop#1294] opened 2018-01-19 09:11 UTC
**Operating System**:  Solus 3.26.2
**Budgie version**:  Budgie 10.4.150 

**The issue encountered**

There is no option to set notifications position on budgie desktop.

Thanks.

**Comment by fossfreedom** [comment] 2018-01-19 09:38
Duplicate of this: https://github.com/budgie-desktop/budgie-desktop/issues/613

**Closed by fossfreedom** 2018-01-19 09:38 UTC
