### ISSUE TITLE
Budgie conflict with AT SPI on Ubuntu Xenial

### ISSUE THREAD

**Issue by IlyaBizyaev** [budgie-desktop/budgie-desktop#419] opened 2016-04-22 15:53 UTC
Hello!
Unfortunately, after Ubuntu 16.04 upgrade, there's a problem that occurs when switching between Unity and Budgie sessions.
On my computer, I have 2 user accounts, and one of them uses Unity, and the other one - Budgie desktop. But now the system gets frozen when switching from Unity to Budgie user. And it basically remains frozen, only displaying the wallpaper, until I kill the `gnome-session-b` process from the system terminal and re-login to Budgie.
That's definitely not a way for me. Could you possibly fix the problem or suggest a solution?

**Comment by IlyaBizyaev** [comment] 2016-04-25 17:44
After a number of reboots, the problem disappeared. It still may happen to new users, but I am anyway not able to reproduce it now - so, closing this issue.

**Comment by IlyaBizyaev** [comment] 2016-04-26 09:59
Sounds strange, but it seems to depend on keyboard layout! I've managed to reproduce the problem by removing "English (US)" keyboard layout, only leaving "Russian". And then it was impossible to launch Budgie at all! Then I've returned it using Unity, and Budgie launched properly.

**Comment by IlyaBizyaev** [comment] 2016-04-27 11:32
Reoccurred today. No input settings were changed => reasons are different.
I have explored the home directory of this user, and here's what I've found:

**~/xsession-errors:**
```
openConnection: connect: Нет такого файла или каталога
cannot connect to brltty at :0
```
**~/xsession-errors.old:** identical.

Maybe that helps.

**Comment by IlyaBizyaev** [comment] 2016-04-27 14:28
The problem is caused by `dbus-daemon` process. Killing it unfreezes the PC.
Is it a Budgie issue, or shell I report it to dbus developers?

**Comment by ikeydoherty** [comment] 2016-04-27 14:43
Probably Budgie and Unity fighting over a single d-bus name.. I need to install Ubuntu I guess and explore this.

**Comment by ikeydoherty** [comment] 2016-07-21 19:30
Can't reproduce here, please confirm its still happening with 10.2.6

**Comment by IlyaBizyaev** [comment] 2016-07-22 14:58
Confirming - still happens.
However, this may be more of an Ubuntu problem, as there's such an issue on Launchpad affecting many people with different DEs: https://bugs.launchpad.net/ubuntu/+source/at-spi2-core/+bug/1285444
In my opinion, what Solus can provide is a workaround - an option to diable AT SPI (see XFCE as an example).

**Comment by ikeydoherty** [comment] 2016-07-22 15:24
We use AT SPI - why would I disable it? Or would you see accessibility disabled for others?

**Comment by IlyaBizyaev** [comment] 2016-07-22 15:38
Sorry, I seem to have a misunderstanding...
Would disabling accessibility for others be a workaround if killing the at-spi-* process loads the desktop?

**Comment by ikeydoherty** [comment] 2016-07-23 10:22
But it seems you're the only person who has the issue, Budgie does *work* on Ubuntu, the Budgie Remix is proof of that. It *obviously* works on Solus (And Fedora, Arch, Gentoo, openSUSE) - disabling accessibility for this seems like an extremely misinformed move.

**Comment by IlyaBizyaev** [comment] 2016-07-23 10:33
Sorry, whom do you mean by others? I thought you mean users that do not need accessibility features.
And again, I want to emphasize that I'm probably the only user who experiences such a problem with Budgie, but there are at least 30 more users affected by the issue on different desktop environments. That is why I suppose that is an Ubuntu issue.
Maybe I get it wrong, but a simple switcher in settings, allowing to disable accessibility if it is unused on a certain PC, seems to be a good workaround. At least some people in the thread on Launchpad fixed the problem on their PCs doing exactly that (yet by far worse means, such as removing execution permissions).

**Comment by ikeydoherty** [comment] 2016-07-23 11:05
Well then it appears to me that this is a problem that *Ubuntu* needs to fix, and not Budgie. Budgie isn't doing anything problematic here, and it works fine on Solus, and other systems. Don't magically claim that those numbers have consequence to Budgie, when none of them relate to it.

The solution here is for Ubuntu to fix its issue

**Comment by IlyaBizyaev** [comment] 2016-07-23 11:11
I don't ;)
Ok, waiting for Ubuntu. Closing this issue.

**Comment by ikeydoherty** [comment] 2016-07-23 11:13
You can keep this open, just link it to the Ubuntu launchpad issue, to show that there issue is affecting upstreams, and shows it is an Ubuntu issue.

**Comment by IlyaBizyaev** [comment] 2016-07-23 11:23
OK.
The problem is caused by an Ubuntu bug and affects people with various desktop environments.
Here's a link to the bug ticket on Launchpad: https://bugs.launchpad.net/ubuntu/+source/at-spi2-core/+bug/1285444

**Comment by ikeydoherty** [comment] 2016-07-23 11:28
No we know that bit :D The Ubuntu people need to know about it, this bug should be linked on Launchpad too so that the bugs are now cross-referenced. Make sense? :)

**Comment by IlyaBizyaev** [comment] 2016-07-23 11:33
Sure. Done :)

**Comment by ikeydoherty** [comment] 2016-07-23 11:45
Thanks :)

**Comment by ikeydoherty** [comment] 2016-10-18 04:46
Please confirm if you still have this issue on 16.10

**Comment by IlyaBizyaev** [comment] 2016-10-18 12:06
Don't have Budgie installed, but you can ask that in the Launchpad issue I have cross-referenced :)

**Comment by fossfreedom** [comment] 2016-10-18 12:08
last comment in the thread referenced says that not encountered on 16.10 - so suggest close this issue.

**Comment by IlyaBizyaev** [comment] 2016-10-18 13:06
It actually says the issue has not been encountered _yet_, and the comment was posted just three days ago - I suggest waiting for at least a week, so that more people upgraded and provided feedback.

**Comment by ikeydoherty** [comment] 2016-10-26 03:57
Need feedback on this or it gets closed soon.

**Comment by ikeydoherty** [comment] 2017-06-25 01:56
"soon" ^ Lol.

**Closed by ikeydoherty** 2017-06-25 01:56 UTC
Labels: ubuntu-specific
