### ISSUE TITLE
Toggling "Notification Pop-ups" in gnome control center doesn't affect all notifiaction pop-ups in Budgie

### ISSUE THREAD

**Issue by arcooke** [budgie-desktop/budgie-desktop#1266] opened 2017-12-10 04:18 UTC
**Operating System**: Solus 3.26.2
**Budgie version**: 10.4

**The issue encountered**

Disabling notification pop-ups doesn't disable all pop-ups, only GNOME shell pop-ups.  See screenshot.  This notification is spawned from Firefox using the Pushbullet extension. 

![](https://i.imgur.com/qAKaPo7.png)

(The over-sized notification is posted as a separate issue #1267)

**Steps to reproduce the issue**

There are other ways to do this, but this is how things are set up on my end.  Not sure off-hand how to reproduce using simpler methods

* Disable pop-up notifications in gnome control center
* Install Firefox (I'm using nightly, 59.0a1)
* Install Pushbullet extension, sign in
* Install Pushbullet on mobile (I use Android), sign in
* Send yourself an email, wait for mobile notification to come through.

**Comment by JoshStrobl** [comment] 2018-03-13 14:17
Effectively a duplicate of #926. Notification changes in GNOME Control Center apply to GNOME Shell, not Budgie.

**Closed by JoshStrobl** 2018-03-13 14:17 UTC

**Comment by Asheboy** [comment] 2018-04-05 11:51
@JoshStrobl Are there settings somewhere in budgie-desktop to configure this?
