### ISSUE TITLE
Budgie crashes when opening Audacious

### ISSUE THREAD

**Issue by gabretana** [budgie-desktop/budgie-desktop#533] opened 2016-08-10 05:08 UTC
First of all my English is terrible, I know
Budgie crashes when I open Audacious, only happens with Audacious.
After this, the panel is hidden, only works Raven and the dialog Alt+F2, I'm using Budgie v10.2.6 ArchLinux 64 bits (also happens in 32 bits)
[Output](https://paste2.org/x3JkBUst)
![](http://i.imgur.com/LMDMykr.png)
[Screenshot 1](http://i.imgur.com/LMDMykr.png)
![](http://i.imgur.com/y8HdSqS.png)
[Screenshot 2](http://i.imgur.com/y8HdSqS.png)
Sorry for the wallpaper...

**Comment by JannikHa** [comment] 2016-10-18 11:38
Using Budgie V10.2.7 (For Arch -> (AUR) **budgie-desktop-git**), not your version, there are no problems regarding this, just tried to repoduce. Maybe it's already a known problem (or similar) which has been fixed in master.

What happens if you let budgie-panel crash, still having audacious opened, and then type in Terminal:

    budgie-panel --replace &

?
If everything fails, try "upgrading" to the [git version](https://aur.archlinux.org/packages/budgie-desktop-git/), it's pretty stable IMO and has plenty more cool features! Though first let's figure out what's happening in your case here.

**Comment by quesada** [comment] 2016-11-13 11:23
trying to replicate on solus 1.2. Bulgie didn't crash, but audacious didn't launch either.

**Comment by JoshStrobl** [comment] 2017-03-01 00:07
Unable to reproduce against latest audacious package in Solus (which saw some changes to enable specification of its plugins as a rundep, which is why it wasn't launching for you @quesada is you likely didn't have those installed) nor against the latest Budgie.

**Closed by JoshStrobl** 2017-03-01 00:07 UTC
