### ISSUE TITLE
Expected behavior for launcher selection

### ISSUE THREAD

**Issue by DerpyCrabs** [budgie-desktop/budgie-desktop#677] opened 2016-10-23 17:47 UTC
First element always selected in alt+f2 launcher on open, but down arrow key doesn't select second element on first press.
I think expected behavior is moving selection on first press of arrow key.
(Maybe first element should also be selected in menu because one doesn't see what program will launch on "enter" press)

**Comment by tristan957** [comment] 2016-10-27 22:58
Noticed this as well

**Comment by hersh-verthun** [comment] 2016-11-06 09:25
That is correct. The behavior is not intuitive. If the first item is already selected, then I should be able to **arrow down** to next item in the list.

**Comment by ikeydoherty** [comment] 2016-11-06 17:23
The arrow key is focused on the GtkEntry, or are we forgetting that its there.. ? The widget focus chain is correct.

**Comment by JoshStrobl** [comment] 2017-02-28 22:02
Can't reproduce on latest Budgie and as this issue has not been replied to by original participants, closing.

**Closed by JoshStrobl** 2017-02-28 22:02 UTC

**Comment by vanitasvitae** [comment] 2017-05-12 22:20
The issue is still present for me (Budgie Desktop 10.3.1).
If there are multiple items in the list, the first one appears to be selected, but in fact the test box has focus. When I press the down key once, the focus switches from the textbox to the first list item. Only the second arrow down switches to the second list item.

Please reopen this issue :)
