### ISSUE TITLE
Taskbar panel stretching across monitors

### ISSUE THREAD

**Issue by jaynus** [budgie-desktop/budgie-desktop#1344] opened 2018-02-26 18:11 UTC
**Operating System**: Ubuntu Budgie 16.04
**Budgie version**: 10.4

Using a triple monitor setup, with my main display being the center screen, the taskbar panel stretches to the right monitor when enough applications fill the taskbar. Am I missing a setting or feature to make these autosize or shrink accordingly? Or is this an incoming feature?

Ive included screenshots of the relevant portions of my two screens here. As you can see, the task list has filled beyond my first monitor, so auto stretches to the second. 

![budgie_main](https://user-images.githubusercontent.com/2880909/36686956-f9f210f4-1adc-11e8-960b-b25a7125583c.png)
![budgie_right](https://user-images.githubusercontent.com/2880909/36686952-f752db94-1adc-11e8-8977-f828cf56c2c1.png)

Ideally, this behavior should be configurable to stack on the same desktop, or shrink, or other options. Ideally, I'd like to lock my task list to the single monitor until I can have a task list per-monitor.

**Comment by fossfreedom** [comment] 2018-02-26 19:10
https://github.com/budgie-desktop/budgie-desktop/issues/1111

This is a duplicate of the above issue.

Thanks

**Closed** 2018-02-26 19:10 UTC
