### ISSUE TITLE
Can't switch languages when in Super menu

### ISSUE THREAD

**Issue by thumos333** [budgie-desktop/budgie-desktop#1306] opened 2018-01-30 05:47 UTC
Hi,
It isn't possible to switch between keyboard layouts when the Super key menu is open. In my case, the languages are English and Russian, while Alt + Space and Shift + Alt + Space are the combinations used to switch to next / previous input source.
Would appreciate very much if this issue is addressed.

Solus version is 3.26.2.
Budgie version is 10.4.

**Comment by JoshStrobl** [comment] 2018-03-13 14:14
Duplicate of #420

**Closed by JoshStrobl** 2018-03-13 14:14 UTC

**Comment by thumos333** [comment] 2018-03-13 14:28
I believe this doesn't duplicate thread #420 . The issue is that I can switch languages when in Super menu, although it remains open.

**Comment by odmin4eg** [comment] 2020-06-09 07:49
I agree with the author, I have the same problem, it causes significant inconvenience to using DE
