### ISSUE TITLE
Wrong icon on spotify notification

### ISSUE THREAD

**Issue by garnieretienne** [budgie-desktop/budgie-desktop#795] opened 2017-02-07 21:24 UTC
**Operating System**:  Solus 2017.01.01.0-Budgie updated
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**

I have the wrong icon (email?) on notification of spotify when new songs are played (see screenshot) in what, I believe, should be the song album cover place.

![screenshot from 2017-02-07 18-48-44](https://cloud.githubusercontent.com/assets/223963/22712165/15151020-ed84-11e6-8fdd-45f9ba9bd92e.png)

My icon theme in this screenshot is Arc, don't known if it's related.

**Steps to reproduce the issue**

Open spotify (installed from Solus third party repository) and start playing titles and observing notifications.

**Comment by garnieretienne** [comment] 2017-02-07 21:27
Seems to be fixed in this PR? https://github.com/budgie-desktop/budgie-desktop/pull/711

**Comment by garnieretienne** [comment] 2017-02-08 13:30
The same icon (the enveloppe) is wrongly used for other notification (seems to be used as a default icon).

![screenshot from 2017-02-08 14-28-45](https://cloud.githubusercontent.com/assets/223963/22739243/223b8784-ee0b-11e6-9b65-30d8d309ec06.png)

**Comment by ikeydoherty** [comment] 2017-02-08 15:07
Not sure what makes it "wrong", it's the fallback icon.

**Comment by ikeydoherty** [comment] 2017-02-08 15:09
What we can do is merge the final 2 parts of that PR, as I think it would be bad form to merge the first one and make Budgie start loading things over the network without a way to switch it off or inform the user.

**Comment by garnieretienne** [comment] 2017-02-08 16:28
> Not sure what makes it "wrong", it's the fallback icon.

I was perceiving it as wrong as to me an envelope is email related (or message related). In this context,  I was assuming something music related (spotify) or battery related (suspend notification). 

I don't known the internal of how icons works, nor if it's the responsibility of the GTK theme instead of budgie, but I think no icon at all could be better than this fallback one.

**Comment by JoshStrobl** [comment] 2017-02-28 20:48
Duplicate of #560

**Closed by JoshStrobl** 2017-02-28 20:48 UTC
