### ISSUE TITLE
Feature: Make budgie compatible with other window managers (like xfwm4)

### ISSUE THREAD

**Issue by ThanosApostolou** [budgie-desktop/budgie-desktop#760] opened 2016-12-23 11:08 UTC
I don't know if this is the right place to request this.

It's really important for me, that the desktop's window manager supports snapping windows to the edges and corners, as well as being able to resize them after you snap them. Since budgie is using libmutter, it can only snap windows to the sides and it doesn't allow you to resize them afterwards. So, I tried budgie (version 10.2.8) on manjaro and tried to use xfwm4 window manager with `xfwm4 --replace` command as I do on mate. It seems to work, but when I open the menu then it doesn't show anything (menu and panel disappear).

Maybe you can fix this for budgie 11, or even better if you can add snapping to corners (as a grid) functionality to budgie-wm (maybe even in such a way that it will be compatible with wayland for the future releases).

**Comment by ikeydoherty** [comment] 2016-12-23 11:15
This is already going to happen with the modularisation of Budgie. Do not forget, however, that certain things are just going to stop working. Chiefly, keyboard shortcuts. No Budgie component uses display-protocol specific hotkey mechanisms, they currently go via the compositor (which right now is `budgie-wm`).

Perhaps for those instances I can add some `--flag`s to the new binaries to allow users of other desktops to add in shortcuts themselves. As Raven and the Panel will be separate processes this will actually be trivial to accomplish architecturally.

**Comment by Vistaus** [comment] 2016-12-23 11:39
Not sure about xfwm, but for me Budgie works fine with i3 on Solus 1.2.1

**Comment by nazar-pc** [comment] 2016-12-23 11:48
I'm using it with Compiz on Ubuntu and it works fine (with few small exceptions). Hotkeys for applications launching and WM actions (like window resizing) are handled by Compiz, multimedia keys (like volume) might be handled via gnome-fallback-media-keys-helper, which works on X11 and is a standalone app.

**Comment by ThanosApostolou** [comment] 2016-12-23 12:24
I managed to take some screenshots in order to show the problems better.

Using xfwm4:
     When the panel is on bot, when I open the menu then the panel and menu dissapear: http://imgur.com/a/h0nFZ
     When the panel is on top, then the desktop disappears (same applications are open at the following picture): http://imgur.com/a/cgVvv

@nazar-pc Using compiz: the panel settings are out of place, http://imgur.com/a/G15HT (maybe this is happening only on manjaro? I don't know).

**Comment by nazar-pc** [comment] 2016-12-23 14:05
Looks like something is really wrong there.
Can you upgrade to latest Budgie 10.2.9? Also which version of Compiz do you have (mine is 0.9.13.1)?
And is there something interesting in terminal output?

I also didn't notice any issues like you have when tried Openbox and Metacity in VM.

**Comment by ThanosApostolou** [comment] 2016-12-23 14:50
@nazar-pc My compiz version is 0.9.13.1 too, but there isn't budgie 10.2.9 in the unstable manjaro repositories yet and I'm not pro enough to compile from source.

I fixed the problem of the 2nd picture (xfwm4 + top panel) by re-enabling xfwm4 compositor, but the other problems are still there. I also tried to mess around with some ccsm settings but no luck.

I also noticed that when I'm using other window managers, then I can't logout (maybe the logout command also depends on `budgie-wm`?).

I think I'll wait for budgie 11 to be released, before I try again.

**Comment by nazar-pc** [comment] 2016-12-23 14:54
Not sure about logout (not using it), but shutdown/reboot works from second or third trial, happens with any WM other than mutter-based. This is one of the issues somewhere deep inside of GNOME stack, you can read discussion here: https://bugs.launchpad.net/bugs/1448418
The problem seems to be purely in UI, it just doesn't show confirmation dialog.

**Comment by ThanosApostolou** [comment] 2016-12-23 15:04
Yeah I believe that budgie should create it's own session too when version 11 is released and stop depending on gnome-session. It would be nice to have its own dconf directory too, something like `/org/budgie` like mate and cinnamon do, so that we can change some advanced settings without messing out with gnome.

Kinda irrelevant, but budgie should also get its own freedesktop name, so that we can use something like `OnlyShownIn=BUDGIE` in a desktop entry when we want it visible on budgie but not on gnome.

**Comment by nazar-pc** [comment] 2016-12-23 15:34
It already works:
```
 nazar-pc  ~  cat /etc/xdg/autostart/budgie-desktop-screensaver.desktop                                                                                                                                                                 
[Desktop Entry]
Type=Application
Name=Screensaver (Budgie Desktop)
Comment=Launch screensaver and locker program
Icon=preferences-desktop-screensaver
Exec=gnome-screensaver
TryExec=gnome-screensaver
OnlyShowIn=Budgie;
NoDisplay=true
X-GNOME-Autostart-Phase=Application
X-GNOME-Autostart-Notify=true
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-screensaver
X-GNOME-Bugzilla-Component=general
```

**Comment by ikeydoherty** [comment] 2016-12-24 06:48
> might be handled via gnome-fallback-media-keys-helper, which works on X11 and is a standalone app.

Uuhhhh no.

**Comment by ikeydoherty** [comment] 2016-12-24 06:50
> Yeah I believe that budgie should create it's own session too when version 11 is released and stop depending on gnome-session.

Yet you don't list *why*.

**Comment by ThanosApostolou** [comment] 2016-12-24 10:42
@ikeydoherty
 > Yet you don't list why.

The main reason I can think of, is for distributions that have gnome as separate desktop environment (I think solus doesn't), so that you can for example change the desktop background on budgie without changing it on gnome desktop when you have both installed (now when you change background on budgie, it affects gnome too as they share too many settings). So maybe a separate session and a dconf directory like `/org/budgie` would allow such changes to happen independently.

**Comment by ikeydoherty** [comment] 2016-12-24 11:13
I don't own budgie.org so it will have to remain /com/solus-project/.

..Which we already have. And the session has nothing to do with the settings, btw. We use `org.gnome.desktop.background` for our wallpaper settings, which we render in budgie-wm ourselves, purely because that is the setting used by `gnome-control-center`.

The issue isn't dropping gnome-session, it's dropping all of GNOME. Which is already an active target.

**Comment by ikeydoherty** [comment] 2016-12-24 11:30
Alright. So maybe it will, now that I own budgie-desktop.org ...

**Comment by snkiz** [comment] 2016-12-24 19:01
Well, GNOME used to do keyboard shortcuts in the session I think, they moved it I believe to mutter but I'm not sure. So fallback needed a shortcuts helper. Most WM's I've used can handle shortcuts. But IMO they are kinda core things I think they should be handled by the session and overridden by WM's. From the perspective of the user I think it makes sense. Thats my two cents. Btw love watching your thought process unravel ikey, long live Budgie-desktop.org!

**Comment by ikeydoherty** [comment] 2016-12-24 19:29
So for us, gnome-settings-daemon has the settings for the keyboard shortcuts, and budgie-wm is the one that actually monitors and fires them (src/wm/keyboard.vala) - this avoids hardcoding X11 which won't be good in future, and more to the point its what GSD kinda forces us to do now since the behaviour moved from there into gnome-shell, and we had to keep up..

**Comment by snkiz** [comment] 2016-12-24 20:14
So the question is are you planing on replacing GSD? Then you could do the shortcuts how ever you like. GNOME Doesn't worry about other WM's, docks or anything else. Thats why we're here right? I don't know I'm sure you figure it out. But I think there is some confusion here with feature requests and the like. People are looking for new features/fixes in 10.2.9 since you've moved 10.2.X in to maintenance, these requests should be marked against 11?

**Comment by ikeydoherty** [comment] 2016-12-24 21:00
Yeah to all intents and purposes 10.x is completely static. While its possible we may see a 10.2.10 come out prior to 11 simply for backported bugfixes - that's it. There are no new features in 10.x, it's done.

In the very near future this issue tracker is going down, and I'll need issues filed against their relevant components to help with organisation. Obviously not all the components exist yet so we'll play it by ear

**Comment by mitchellurgero** [comment] 2017-01-15 00:33
Why not just move to xfcm?

**Comment by ikeydoherty** [comment] 2017-01-15 15:37
Closing due to lack of relevancy.

**Closed by ikeydoherty** 2017-01-15 15:37 UTC

**Comment by ikeydoherty** [comment] 2017-01-15 16:24
To further clarify as I was in a rush: I want Budgie 11 to be modular, and you pick what bits you want. I mean the general original conversation isn't quite applicable anymore.

**Comment by y1n0** [comment] 2018-10-14 20:57
@Vistaus How do you manage to use i3 wm with budgie-desktop?
