### ISSUE TITLE
"Settings" causes desktop to freeze

### ISSUE THREAD

**Issue by jpalmieri** [budgie-desktop/budgie-desktop#839] opened 2017-03-30 15:55 UTC
**Operating System**: e.g. Ubuntu 16.10
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**
When loading "Settings", the screen freezes momentarily (for 10-20 seconds; no mouse response), and sometimes stays frozen, although I haven't been able to reliably reproduce the latter. 

**Steps to reproduce the issue**
Open the "Settings" application (it happens without fail for me).

**Other notes**
I'm running this on an old [Macbook 4,1](http://www.everymac.com/systems/apple/macbook/specs/macbook-core-2-duo-2.4-white-13-early-2008-penryn-specs.html) with the following modifications:
RAM upgrade to 4GB
SSD 120GB

That being said, I don't expect much attention to this issue, since I have a crappy laptop. 😉 
The desktop works brilliantly otherwise on my old piece of plastic, though. Thanks for the hard work!

**Comment by fossfreedom** [comment] 2017-03-30 17:16
From a terminal run

    gnome-control-center

Any messages displayed in the terminal after the 20 secs it will take to launch?

**Comment by jpalmieri** [comment] 2017-03-30 19:11
Looks like I'm missing some stuff:

```
joe@joe-MacBook:~$ gnome-control-center

** (gnome-control-center:8314): WARNING **: Ignoring launcher deja-dup-preferences (missing desktop file)

** (gnome-control-center:8314): WARNING **: Ignoring launcher landscape-client-settings (missing desktop file)

** (gnome-control-center:8314): WARNING **: Ignoring launcher language-selector (missing desktop file)

** (gnome-control-center:8314): WARNING **: Ignoring launcher ubuntuone-installer (missing desktop file)
```

**Comment by fossfreedom** [comment] 2017-03-30 19:25
those warnings are expected.  They don't cause an issue on my 16.10 install.

Any chance you can download th current daily 17.04 ISO and boot up into the live session and see if settings still takes 20 secs?

alternatively -  just wait for a couple more weeks until 17.04 is officially released to retest.

**Comment by jpalmieri** [comment] 2017-03-30 19:32
I'll give it a shot! Where can I find the 17.04 download?

**Comment by fossfreedom** [comment] 2017-03-30 20:21
http://cdimage.ubuntu.com/ubuntu-budgie/daily-live/current/

**Comment by jpalmieri** [comment] 2017-03-31 04:59
@fossfreedom I was able to try 17.04 and still had the same issue. 😕 

Launching settings with `gnome-control-center` on 17.04 had similar warnings, but no other output.

**Comment by fossfreedom** [comment] 2017-03-31 06:50
networking issue?  Are you behind a proxy or firewall?  Or are you just using a standard broadband and your ISP router?

**Comment by jpalmieri** [comment] 2017-03-31 17:21
Doesn't seem to be network related. I've had the same problem at multiple locations, two of them being home networks with just standard broadband and router.

**Comment by JoshStrobl** [comment] 2017-04-28 08:11
Can you reproduce this issue with Budgie 10.3 and is this Ubuntu specific? Unable to reproduce elsewhere.

**Comment by fossfreedom** [comment] 2017-04-28 08:17
unable to reproduce this in 17.04 - and hasn't been reported elsewhere.

**Comment by ikeydoherty** [comment] 2017-04-28 08:18
Possibly a driver/stack bug then

**Comment by ikeydoherty** [comment] 2017-06-25 01:29
Closing as no action

**Closed by ikeydoherty** 2017-06-25 01:29 UTC
