### ISSUE TITLE
Budgie: Can't Search for Displays or Details using Names

### ISSUE THREAD

**Issue by SolarLune** [budgie-desktop/budgie-desktop#872] opened 2017-04-20 21:51 UTC
Yo, 'sup.

**Operating System**: Solus 2017.04.18.0
**Budgie version**: budgie-desktop 10.3.1

**The issue encountered**

So if you want to search for the display configuration tool, "Displays", you can't type "Displays" into the Budgie search box. You have to type "Monitors". 

Same thing with the Details window, showing you info about your system - you can't type "Details", you have to type "About".

It might be a good idea to ensure that

1) The names of items in the menu are valid to search by, and
2) Exact and partial matches to a name are driven to the top of the list, above any others (so searching "Steam" will return Steam first, and Steam games _afterwards_).

**Comment by JoshStrobl** [comment] 2017-04-28 07:54
Generally speaking, a duplicate of #397. Budgie menu's search functionality needs some love and better matching.

**Closed by JoshStrobl** 2017-04-28 07:54 UTC
Labels: duplicate
