### ISSUE TITLE
Tilte bar of maximized window placed "under" top panel

### ISSUE THREAD

**Issue by DrMarkuse** [budgie-desktop/budgie-desktop#1155] opened 2017-09-12 22:04 UTC
Using Solus 3 with Budgie 10.4 on a ThinkPad T430 (newly installed and language set to German).
When moving the panel to the top maximized windows are placed "under" the panel (see annexed screenshot); the title bar is obscured. 
![budgie -- panel on top covers window buttons](https://user-images.githubusercontent.com/31903781/30350190-feefb15a-9815-11e7-9090-6ca4cf7c7966.png)
There is a small part of the application window by which it can be accessed to resize it, but I guess the top bar of the application should still be visible.

**Comment by niyasc** [comment] 2017-09-13 06:13
Duplicate of https://github.com/budgie-desktop/budgie-desktop/issues/1137

**Closed** 2017-09-13 06:50 UTC
Labels: duplicate
