### ISSUE TITLE
[Panel] When too many windows are open, panel contents get pushed off-screen

### ISSUE THREAD

**Issue by mr-islam** [budgie-desktop/budgie-desktop#1404] opened 2018-05-01 12:01 UTC
**Operating System**: e.g. Solus 3.9995 (that feels like a joke :stuck_out_tongue: )
**Budgie version**: Budgie 10.4

**The issue encountered**:

When there are a lot of windows open, the display of open windows on the panel expands — causing the panel contents overall to overflow, pushing the bottom applets off-screen. See screenshot:

![screenshot from 2018-05-01 15 24 36](https://user-images.githubusercontent.com/17675428/39469969-829e89d8-4d54-11e8-823e-943c54996fe2.png)

**Steps to reproduce the issue**

Open window after window of applications, depending on your icon size and panel orientation, until there are more open then can fit on the panel. Voilá!

**Comment by fossfreedom** [comment] 2018-05-01 12:04
duplicate of https://github.com/budgie-desktop/budgie-desktop/issues/83 and #855

**Closed by fossfreedom** 2018-05-01 12:04 UTC
