### ISSUE TITLE
Always hide panel

### ISSUE THREAD

**Issue by JustPerfection** [budgie-desktop/budgie-desktop#1393] opened 2018-04-28 21:53 UTC
How can I have always hide panel?

**Operating System**: e.g. Ubuntu 18.04
**Budgie version**: i.e. Budgie 10.4

**Comment by fossfreedom** [comment] 2018-04-28 22:02
Why would you want to always hide the panel? You do have the autohide option for a panel in budgie settings.

**Comment by JustPerfection** [comment] 2018-04-28 22:07
I know about auto hide, but It doesn't work just like what I want. I want a panel that only shows when I do mouse over on that area.

**Comment by fossfreedom** [comment] 2018-04-28 22:11
Duplicate of https://github.com/budgie-desktop/budgie-desktop/issues/1257

**Closed by fossfreedom** 2018-04-28 22:11 UTC
