### ISSUE TITLE
Budgie Run Dialog too small

### ISSUE THREAD

**Issue by GladOSkar** [budgie-desktop/budgie-desktop#791] opened 2017-02-04 10:26 UTC
**Operating System**: Solus 2017.01.01.0 64-Bit
**Budgie version**: Budgie 10.2.9-111

**The issue encountered**

After the last updates, the budgie-run-dialog is only about half as wide as it was before.
I guess this is not intended.

**Environment**

Using i3 on a 1920x1080 display

**Steps to reproduce the issue**

execute "budgie-run-dialog"

**Image**
![rundialogbug](https://cloud.githubusercontent.com/assets/9497832/22617749/aef050fc-eacc-11e6-9204-fef523082be0.png)

**Comment by JannikHa** [comment] 2017-02-04 10:55
I think it is alreay being worked on. From what I know, Ikey said that this problem is related to GTK 3.22 and soon fixed :)

**Comment by JoshStrobl** [comment] 2017-02-28 21:07
Closing as a duplicate of #800 since resolving the Budgie Run Dialog is a target for 10.3

**Closed by JoshStrobl** 2017-02-28 21:07 UTC
