### ISSUE TITLE
[Feature] Can you add window sorting in the taskbar?

### ISSUE THREAD

**Issue by skullscream** [budgie-desktop/budgie-desktop#956] opened 2017-06-18 22:19 UTC
I don't think guidelines are relevant here. I'm using the latest version of budgie desktop from arch repository.

So I'd like there to be window sorting, like there's on Windows' taskbars.

See how chromium opens up twice for two windows and there are two instances in the taskbar, it would be nice to see both instances grouped into one. (And maybe also adding new window and new incognito window into right click options)
![screenshot from 2017-06-19 00-17-17](https://user-images.githubusercontent.com/18366085/27264717-010cc0ce-5485-11e7-8277-2d7d023ba823.png)

**Comment by ikeydoherty** [comment] 2017-06-19 00:33
This is a duplicate of at least two bugs. The right click actions come from the .desktop file not Budgie itself  and I know there is another task wrt grouping #439 #4 etc) - i'll track them in the appropriate tasks.

**Closed by ikeydoherty** 2017-06-19 00:33 UTC

**Comment by skullscream** [comment] 2017-06-19 07:13
Hope we'll get that implemented soon. I would if I knew what I'm doing :)

**Comment by ikeydoherty** [comment] 2017-06-19 11:08
It'll be a Budgie 11 thing no doubt.

**Comment by skullscream** [comment] 2017-06-19 15:05
Thanks. You got a heart :D
