### ISSUE TITLE
NetworkManager applet grayed out even though active

### ISSUE THREAD

**Issue by tristan957** [budgie-desktop/budgie-desktop#864] opened 2017-04-18 02:06 UTC
**Operating System**: Solus current
**Budgie version**: Budgie 10.3
**The issue encountered**
The NetworkManager applet seemed to undergo a regression upon today's update. Although I'm currently connected to Wi-Fi, the applet is displaying a grayed out version akin to the sound indicator when muted or the bluetooth indicator when bluetooth is turned off.

Important to note that this doesn't happen on every icon theme. It seems to happen on Moka, Faba, and Paper for the themes that I have installed.
 ...
**Steps to reproduce the issue**
Choose one of these icon themes, and look at network manager.
 ...

It is possible this is not a budgie-desktop issue.

**Comment by ikeydoherty** [comment] 2017-04-18 02:39
Hm sure this isn't a GTK theme thing? Keep in mind `nm-applet` comes from `network-manager-applet` not budgie

**Comment by tista500** [comment] 2017-04-18 14:13
Ugghh, everybody says "Yeah Gtk+ theme's fault"... :(

I've added a workaround for this issue to Adapta: https://github.com/adapta-project/adapta-gtk-theme/commit/d6e991e2f809fd9d6642eafb699b39f33e24a0b6

Seems Nm-applet puts the 16px icons inside the 24px clip-area even if budgie-panel's height had 37px or taller. 16px icons are not suitable for re-colouring from theme-side, should be drawn with 24px symbolic icons instead...

As original reporter said, Paper has dark-foreground 16px icons in `16x16/panel` directory, maybe Moka, too.

Regards.

**Comment by ikeydoherty** [comment] 2017-04-18 14:25
@tista500 ehm I had no clue the OP was using Adapta, they only mentioned icon themes. I also said "theme *thing*" not "theme's *fault*", key difference :)

The reason I suspected a conflict with GTK theme (no doubt from 3.24/Budgie 10.3 changes) - was because we do no internal recolouring of trays.

**Comment by tristan957** [comment] 2017-04-20 18:35
@ikeydoherty I guess it is the GTK theme's fault. Just thought It was weird that it would happen right after the 10.3 update

**Comment by ikeydoherty** [comment] 2017-04-20 19:02
It's Budgie's fault for changing the natray stuff, so the poor theme authors now have to work around that

**Comment by fossfreedom** [comment] 2017-04-20 19:15
![ubuntu budgie 16 10 running - oracle vm virtualbox_006](https://cloud.githubusercontent.com/assets/996240/25248387/00746e26-2606-11e7-9f86-7f8e01c218c4.jpg)

Are we talking about this issue?  noticed that with default Arc-Darker on upgrade to 10.3 nm-applet is greyed out.  rolling back to 10.2.9 all is well.

**Comment by tristan957** [comment] 2017-04-20 19:21
@fossfreedom that's exactly what the issue is about. Seems to be a theming issue though, not related to Budgie

**Comment by fossfreedom** [comment] 2017-04-20 19:27
um - ok so all current budgie-compatible themes needs the something like what @tista500 has done?

**Comment by tista500** [comment] 2017-04-20 21:13
@tristan957,

Gtk+ theming issue!?
Oh, please...
1. In 10.2.9, the GtkWidget of TrayIcon was allocated by 24px x 24px if the parent GtkBox container had 24px x 24px or larger. But 10.3, TrayIcon's allocation became 16px x 16px in 24px GtkBox container.
2. In Moka, and Paper icons might have the dark-foreground 16px icons in `16x16/panel` directory (those icons are not able to be re-coloured from Gtk+ theme-side anyway, at least with Paper icon theme).
3. This happens in the current Gnome-Panel/Mate-Panel as well. But in those panels, this specific selector (node-name) can define the default (minimum)-icon-size of NaTrayIcons: 
```
na-tray-applet {
  -NaTrayApplet-icon-padding: 0 2;
  -NaTrayApplet-icon-size: 24;
}
```
4. The dark-foreground 16px icon sets are not suitable for dark-panels. 

@fossfreedom,

Umm, I don't want to suggest such workaround to other Gtk+ theme authors. :(
Because my workaround does not work if budgie-panel's height was set to 36px or smaller. Once 16px allocated nm-applet icons are loaded, there's few things to do from Gtk+ theme-side (with Paper and Moka icon theme at least). See Adwaita icon theme. They have coloured (non-monochromatic) icon sets in 16px panel directory. Those coloured icon sets work out of the box in both light/dark variants without re-colouring from Gtk+ theme-side (although those are ugly for Material Design), and those coloured icons are also OK even if those were put into GtkMenuItems in popup-ed context-menus in both light/dark variants.

So my workaround is currently my best effort from Gtk+ theme-side without few side-effects in backward compat (10.2.9) though, however, for me, that was very semantically wrong...

Regards.

**Comment by ikeydoherty** [comment] 2017-04-22 20:40
^ @tista500 I don't know if that change is going to affect your workaround or not sorry, I'm hopeful that it all justs stays fixed now.

**Closed** 2017-04-22 20:39 UTC

**Comment by tista500** [comment] 2017-04-22 22:11
@ikeydoherty I confirmed https://github.com/budgie-desktop/budgie-desktop/commit/f4e1b949cbbf8886c0ae12a3b528aed5a2d48ae1 could load 22px icons like 10.2.9. And then I can drop my workaround... :)

Thanks so much!

**Comment by ikeydoherty** [comment] 2017-04-22 22:41
Sorry for causing you more work @tista500 - I'll make sure to include this in my future tests. BTW, Adapta on 10.3 looks *gorgeous*. Like, I know I'm infamous for "not liking MD" - but I'm using it Adapta all the time now. Alt+tab, Raven ... <3

**Comment by tista500** [comment] 2017-04-23 00:34
Oh no need to be sorry, Ikey! I'm really happy this issue was fixed because Budgie is the primary desktop environment for me.

> Adapta on 10.3 looks gorgeous. 

Wow thanks again. Have a nice weekend! :-)

**Comment by ikeydoherty** [comment] 2017-04-23 00:48
You too :]
