### ISSUE TITLE
budgie panel reset method does not work?

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#764] opened 2017-01-01 01:27 UTC
**Operating System**: e.g. Debian Stretch/Ubuntu 16.10/Ubuntu 17.04
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**

budgie-panel --reset --replace 

This does not reset the panel - I see the following in the terminal:

```
$ ** Message: manager.vala:294: Reseting budgie-panel configuration to defaults
(budgie-panel:26353): GLib-GIO-CRITICAL **: g_settings_reset: assertion 'key != NULL' failed

** Message: libsession.vala:50: DESKTOP_AUTOSTART_ID not set, session registration may be broken (not running budgie-desktop?)

```

The old dconf -f method does however still work.

    dconf reset -f /com/solus-project/budgie-panel/

thoughts on how to debug this?

**Comment by ikeydoherty** [comment] 2017-01-01 10:40
What version of glib & dconf are you using?

**Comment by fossfreedom** [comment] 2017-01-01 11:15
on 16.10, 17.04 - glib (libc6) 2.24-3, dconf (libdconf1) - 0.26.0
stretch - glib 2.24-8, dconf( libdconf1) - 0.26.0

**Comment by fossfreedom** [comment] 2017-01-05 00:13
hmm - I don't think using null here is allowed - line 296 https://github.com/budgie-desktop/budgie-desktop/blob/master/src/panel/manager.vala

https://developer.gnome.org/gio/stable/GSettings.html#g-settings-reset - nothing here about null doing a complete tree reset - I assume a specific key value is required.  Anyway I assume this this is working on Solus - so very weird why its not working on debian

**Comment by ikeydoherty** [comment] 2017-01-05 00:16
We use `.reset(null)` when removing panels too. I spoke with `dconf` devs about this a long while back, it's how you achieve reset on relocatable schemas

**Comment by ikeydoherty** [comment] 2017-01-05 00:18
Solus:

Name                : dconf, version: 0.26.0, release: 14
Name                : glib2, version: 2.48.1, release: 28

**Comment by fossfreedom** [comment] 2017-01-05 09:57
ah - I wonder - this problem doesnt occur in Ubuntu 16.04 - glib2 version is the same as solus

In yakkety glib2 is 2.50 and zesty is tracking 2.51 currently.  I wonder if this is a glib2 2.50 or later issue?

**Comment by ikeydoherty** [comment] 2017-01-05 12:00
Certainly would seem so yeah

**Comment by ikeydoherty** [comment] 2017-01-24 05:40
Confirmed, 2.50. is the breaker. They added an assertion in when they said this behaviour would be retained....

**Comment by ikeydoherty** [comment] 2017-01-24 05:46
https://bugzilla.gnome.org/show_bug.cgi?id=744678

Turns out they actually removed the existing functionality, breaking Budgie resets completely.
Only alternative is now we hook directly into dconf, adding further bloat.

**Comment by ikeydoherty** [comment] 2017-01-24 06:19
I'll look more into this over the week and we'll get a new update out to fix these issues. Can't have this regression affecting you .. Also when we do Budgie 11 we really need to build it in a way that we can test unstable builds of Budgie against newest libs so we're always prepared..

**Comment by ikeydoherty** [comment] 2017-04-16 20:55
(Finally) fixed in https://github.com/budgie-desktop/budgie-desktop/commit/4656777855c467ce90316e750a2fb54e200f52ac

**Closed by ikeydoherty** 2017-04-16 20:55 UTC
Labels: bug
