### ISSUE TITLE
Mounted device icon overlays desktop ones 

### ISSUE THREAD

**Issue by mmeinert** [budgie-desktop/budgie-desktop#927] opened 2017-05-19 15:52 UTC
**Operating System**: Solus 2017.04.18.0
**Budgie version**: 10.3.1

**The issue encountered**

The desktop icon of a mounted device overlaps another one.

Without mounted device : 
![unmount](https://cloud.githubusercontent.com/assets/2050640/26255176/1812fd80-3cb9-11e7-9638-8a1a9b0772fa.png)
With SDCARD mounted : 
![mount](https://cloud.githubusercontent.com/assets/2050640/26255191/2131ecfa-3cb9-11e7-8b30-b3aef7daf15d.png)

Same behaviour with USB flash drive

I tried the options "keep aligned" and "organize by name" without another behaviour. 

**Steps to reproduce the issue**

Put SD card in enclosure, open "Files" (nautilus), click on the device you wish to "mount and open".
/run/media/my_name/dev_name is created, the icon placed on the desktop overlaps one on the desktop instead an empty place

**Comment by fossfreedom** [comment] 2017-05-19 15:59
The background icons is text is provided by Files (Nautilus) and therefore this isn't a budgie-desktop issue.

Changing the icon size in Files may help here - but there is only a finite space in the overall image + text square space that is available hence why you get certain amount of overwriting.

**Comment by MaxJonasG** [comment] 2017-05-21 09:13
@fossfreedom but the problem is that the SD card is shown in the same space as the word Document, not that the SD description overlays the image

**Comment by fossfreedom** [comment] 2017-05-21 09:21
sure - but this is still a nautilus issue - so perhaps better on the gnome tracker (assuming it isnt already there) https://bugzilla.gnome.org/.

Closing this since its not a budgie-desktop issue.

**Closed by fossfreedom** 2017-05-21 09:21 UTC
