### ISSUE TITLE
Menu and launcher close on layout switch

### ISSUE THREAD

**Issue by DerpyCrabs** [budgie-desktop/budgie-desktop#675] opened 2016-10-23 17:36 UTC
If i switch keyboard layout with win+space it will close menu or launcher. It's annoying and launchers from other DE don't have this issue.
Steps to reproduce:
1. Open menu or launcher
2. Try to switch layout with win+space in order to search program name in other language
3. Menu or launcher close
I can reproduce it on 10.2.8 and git version.

**Comment by ikeydoherty** [comment] 2016-10-23 21:06
To ask the dumbest of possible questions here, but why can't you change your layout first and then open the menu? Seems kinda obvious

**Comment by DerpyCrabs** [comment] 2016-10-24 03:17
For that i must check my layout every time i want to open program. It's slower than correct 1 letter. Also i have program names in different languages and must choice layout before opening menu.
Other launchers allow me to switch layout when they open.

**Comment by ikeydoherty** [comment] 2016-10-24 06:09
True enough. Ok well it's not something that's easily fixable until the rewrite so that's when we'll do it

**Comment by JoshStrobl** [comment] 2017-04-28 08:29
Duplicate of #420.

**Closed by JoshStrobl** 2017-04-28 08:29 UTC
Labels: duplicate
