### ISSUE TITLE
Wi-fi icon bugged on system tray

### ISSUE THREAD

**Issue by th3math3us** [budgie-desktop/budgie-desktop#1290] opened 2018-01-07 14:10 UTC
**Operating System**: e.g. Solus 3.26.2
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

https://i.imgur.com/g8NPRci.png

There's an icon behind the other when the status changes.
Even with the Papirus icon theme or any other icon theme it still happens.
I tried to remove the system tray from the panel and re-add, but it didn't work.

**Steps to reproduce the issue**

That's happening since the installation, when I start up Solus.

**Comment by nextgensparx** [comment] 2018-01-14 20:08
Duplicate of #1249

**Closed** 2018-01-14 20:22 UTC
