### ISSUE TITLE
Budgie Panel is Larger Than Configured

### ISSUE THREAD

**Issue by jGleitz** [budgie-desktop/budgie-desktop#1144] opened 2017-09-09 17:25 UTC
When setting the top panel’s height `x`px with `x` < 35, it is displayed with a height of 35px. But a maximised window starts `x`px from the top of the screen. Because of that, the panel overlaps the window.

20px | 35px
----|----
![20px 1](https://user-images.githubusercontent.com/4305652/30242314-63b17be8-9594-11e7-8977-0f16f435d61f.png) | ![35px 1](https://user-images.githubusercontent.com/4305652/30242315-6999a68e-9594-11e7-865e-142b00a153d5.png)
![20px 2](https://user-images.githubusercontent.com/4305652/30242316-6fa7cb64-9594-11e7-83a6-dea6803e2370.png)|![35px 2](https://user-images.githubusercontent.com/4305652/30242321-73e03e8c-9594-11e7-9219-b885a802cfad.png)

As you can see, the panel has a height of 35px in both cases. If the panel height is set to 20px, the maximized window starts 20px from the top of the screen, making the panel overlap it.

This issue only occurs for panel sizes < 35px. For 35px and more, everything works as expected

### Steps to reproduce
 * Download the [latest Ubuntu Budige 17.10 Build](http://cdimage.ubuntu.com/ubuntu-budgie/daily-live/current/HEADER.html) and run a live session
 * Open Raven, cklick on the cog to open budgie settings and go to the panel settings
 *  Set the panel height to something below 35px and see that it overlaps maximized windows

**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.4

**Comment by sstallion** [comment] 2017-09-10 23:47
I'm affected by this as well using a 32px height on Ubuntu 16.04.3 LTS

**Comment by fossfreedom** [comment] 2017-09-13 08:58
duplicate of #1137

**Closed by fossfreedom** 2017-09-13 08:58 UTC
Labels: duplicate
