### ISSUE TITLE
Menu reopens on longpress

### ISSUE THREAD

**Issue by DerpyCrabs** [budgie-desktop/budgie-desktop#674] opened 2016-10-23 17:33 UTC
Menu closes on "windows" button press but if one holds a little longer it will reopen on release.
Steps to reproduce:
1. Open menu
2. Press "windows" button to close it
3. Hold it a little
4. Menu will close and open again on release
I can reproduce it on 10.2.8 and git version.

**Comment by JannikHa** [comment] 2016-10-23 17:49
Isn't that an intended behaviour?

**Comment by DerpyCrabs** [comment] 2016-10-23 18:04
Gnome shell's overview and pantheon's slingshot doesn't reopen. I find it annoying because there is too little time to release "windows" key and i almost always reopen menu because of it.

**Comment by ikeydoherty** [comment] 2016-10-23 21:09
Budgie's menu toggles on the button-release event. Not sure what you think either GNOME Shell or Pantheon have to do with this. I find it odd you have no time to release the key seeming you said this is a **long press**. Help me out here I'm confused as shit.

**Comment by DerpyCrabs** [comment] 2016-10-24 03:23
Long press is a bad decision. It's just a little longer. Budgie's menu closes on windows press and opens on release. Gnome shell's overview opens and closes on release and i don't have problem like this.

**Comment by JoshStrobl** [comment] 2017-02-28 21:54
Closing as duplicate of #605

**Closed by JoshStrobl** 2017-02-28 21:54 UTC
