### ISSUE TITLE
Removing keyboard layout logs you out and disables ability to log back in

### ISSUE THREAD

**Issue by NigelGreenway** [budgie-desktop/budgie-desktop#740] opened 2016-11-23 21:08 UTC
**Operating System**: Solus 1.2.1 (Ran within a VirtualBox machine)
**Budgie version**: 10.2.8

**The issue encountered**

Removing the English(US) keyboard layout ends the session and returns back to the login screen. When logging back in it will crash and return back to the login screen.

**Steps to reproduce the issue**

 - Install OS
 - Remove second keyboard layout
   - Try to log back in

**Comment by ikeydoherty** [comment] 2016-11-23 21:11
Do you have the keyboard layout indicator present..?

**Comment by ikeydoherty** [comment] 2016-11-23 21:11
Rather, did you..

**Comment by NigelGreenway** [comment] 2016-11-23 21:13
@ikeydoherty present in the system tray?

**Comment by NigelGreenway** [comment] 2016-11-23 21:17
I can recreate tomorrow with a fresh install if that helps? Could also log in and export a log too? Just not sure which log would help?

**Comment by NigelGreenway** [comment] 2016-11-23 22:34
@ikeydoherty I noticed this commit, a65303a8, would it be worth me building budgie on my install? Would like to help but not sure where to start?

**Comment by ikeydoherty** [comment] 2016-11-23 23:23
That is in the Solus package already

**Comment by NigelGreenway** [comment] 2016-11-24 08:38
So, from a fresh install and without updates I have removed the `English (US)` keyboard layout and it has done the same. The indicator was not showing in the panel.

Is there are log I can look at?

**Comment by Robotmike1966** [comment] 2016-11-24 10:34
If helpful:
- I created a fresh Solus in a VirtualBox
- updated everything in original language
- rebooted
- settings dialog: added German, removed English
- Crash, loginscreen reappeared
- did one login try
- had crash again
-waited for login screen
- ctrl alt f1, login on terminal
- journalctl -b -o export > journal.txt

Append this file here. (408 kB)
[journal.txt](https://github.com/budgie-desktop/budgie-desktop/files/611054/journal.txt)

**Comment by rcx** [comment] 2016-12-06 10:25
I have a related problem, I guess. 

When I add Russian keyboard layout, switch to it (use it, etc.) and log out of the system, or when the system locks due to the inactivity, I am introduced with a login screen that doesn't accept the password. Note that I use English letters for my password. 

I suppose that login screen doesn't support language switching. I had to go back to Windows, after clean installing Solus 2 times, due to this bug. It is really annoying. 

Prompt action on this matter would be highly appreciated.

**Comment by niyasc** [comment] 2016-12-06 14:02
> I have a related problem, I guess.
> 
> When I add Russian keyboard layout, switch to it (use it, etc.) and log out of the system, or when the system locks due to the inactivity, I am introduced with a login screen that doesn't accept the password. Note that I use English letters for my password.
> 
> I suppose that login screen doesn't support language switching. I had to go back to Windows, after clean installing Solus 2 times, due to this bug. It is really annoying.
> 
> Prompt action on this matter would be highly appreciated.

@rcx 
This appears like a problem having roots on `gnome-screensaver` and that issue is known for more than 3 years. You can find related discussions [here](https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/1244548)

**Comment by rcx** [comment] 2016-12-06 15:00
@ikeydoherty It seems that this is a long-lived bug, any prospects of fixing it? Maybe adding a  language pick menu in the lock screen would be a good temporary fix?

**Comment by niyasc** [comment] 2016-12-06 18:05
Well. The lock screen does not support language switch shortcut. Though you can see language code on right side of password field and it can be changed by mouse click. ( have n't checked in Solus, but that is the case on **budgie-remix** 16.40)

**Comment by rcx** [comment] 2016-12-07 02:56
Weird. Nothing happens, when I click on the language code on the right side. Let me check in VM.

**Comment by NigelGreenway** [comment] 2016-12-07 08:29
When I have used budgie-remix, I was unable to reproduce this error, only producible on Solus, if that helps?

**Comment by rcx** [comment] 2016-12-08 07:08
I have install Solus on my laptop again and now I realized that when I log out I can see the menu to change the language. But when the system locks due to inactivity then there is no way to switch languages and log in using my English password.

**Comment by RDR8** [comment] 2017-02-05 19:22
As a workaround for the OP, try `gsettings set org.gnome.desktop.input-sources current 0` at a shell prompt, i.e, Ctrl-Alt-F2. This resets the keyboard layout to the default.

**Comment by NigelGreenway** [comment] 2017-02-09 10:58
Will try that this weekend. Thank you @RDR8 :+1:

**Comment by RDR8** [comment] 2017-02-09 17:49
In #741 , @CarlosZaldivar mentions restarting budgie-wm. I think one could do this with systemctl from the same terminal where gsettings was run so that no reboot is needed but I didn't test that. I shamelessly rebooted.

**Comment by fu-sen** [comment] 2017-02-22 04:58
I confirmed this problem with Ubuntu Budgie 17.04 Daily Build. I am shooting that movie:
https://www.youtube.com/watch?v=cSMkgH_ei0U
Playback from 21:30

**Comment by fu-sen** [comment] 2017-02-22 05:58
I confirmed it with Solus. Currently Solus seems to have improved this problem.
I will test again after getting desktop updates with Ubuntu Budgie 17.04.

**Comment by valentinul** [comment] 2017-04-13 11:41
This should be reopen as it is still causing issues ...

**Comment by fossfreedom** [comment] 2017-04-13 11:46
@valentinul what distro are you using?

**Comment by ikeydoherty** [comment] 2017-04-13 12:56
I'm gonna guess a distro without that patch (like stable Solus)

**Comment by ikeydoherty** [comment] 2017-04-16 20:58
Confirmed this is resolved in git and will be part of 10.3 (in an hour or so)

**Closed by ikeydoherty** 2017-04-16 20:58 UTC
