### ISSUE TITLE
FR: Window Management

### ISSUE THREAD

**Issue by arnegoeteyn** [budgie-desktop/budgie-desktop#765] opened 2017-01-02 17:12 UTC
Is there already some more functionality for managing window tiling? Right now all I know is that mod+left, mod+right, mod+up, mod+down will relocate windows. What I would be looking for is something like gTile for GNOME.

https://extensions.gnome.org/extension/28/gtile/

**Comment by Vistaus** [comment] 2017-01-06 16:12
Nope. But work on Budgie 11 is ongoing and starting with v11, it will not be as depended on GNOME as it is right now so more features like this could be added.

**Comment by JoshStrobl** [comment] 2017-02-28 21:28
Actually marking as duplicate of #734

**Closed by JoshStrobl** 2017-02-28 21:28 UTC
Labels: enhancement
