### ISSUE TITLE
[Feature request] Locally integrated menues

### ISSUE THREAD

**Issue by luispabon** [budgie-desktop/budgie-desktop#712] opened 2016-11-07 09:59 UTC
The lack of this feature is the only thing keeping me in Ubuntu / Unity at the moment. Locally integrated menues are super-useful for those of us on laptops where vertical real estate is at a premium by making use of:
 * Window decorations to place the menu when windowed
 * Top panel to place the menu when maximised

See demonstration (towards the end of the vid) at 
https://www.youtube.com/watch?v=teAFgtHWDso

**Comment by fossfreedom** [comment] 2016-11-07 11:07
duplicate of this: https://github.com/budgie-desktop/budgie-desktop/issues/542

**Comment by ikeydoherty** [comment] 2016-11-07 11:34
Closing, cheers

**Comment by Vistaus** [comment] 2016-11-08 19:11
It's not closed yet :wink:

**Comment by ikeydoherty** [comment] 2016-11-08 19:18
blah.

**Closed by ikeydoherty** 2016-11-08 19:18 UTC
