### ISSUE TITLE
"Super+Shift+Tab" not working

### ISSUE THREAD

**Issue by sidahmed-malaoui** [budgie-desktop/budgie-desktop#945] opened 2017-06-08 10:07 UTC
**Operating System**: ubuntu-budgie 17.04
**Budgie version**: 10.3.1

**The issue encountered**
Can't use the shortcut `Super+Shift+Tab` to reverse switch between applications. Only the `Super+Tab` works.
**Steps to reproduce the issue**
I just installed the system and did an upgrade, tried the reverse switch, but it doesn't work.

Please fix this issue, because it really bothers me that I can't switch back between applications.

**Comment by fossfreedom** [comment] 2017-06-08 15:25
Duplicate of this https://github.com/budgie-desktop/budgie-desktop/issues/917

**Closed by fossfreedom** 2017-06-08 15:25 UTC
