### ISSUE TITLE
'pin to panel' is missing for snap apps

### ISSUE THREAD

**Issue by n8v8R** [budgie-desktop/budgie-desktop#1178] opened 2017-10-02 11:15 UTC
**Operating System**: Solus 3 64-bit
**Budgie version**: budgie-desktop 10.4

**Comment by JoshStrobl** [comment] 2017-10-22 15:32
Closing as a duplicate of #1180, which has more information than this issue. Please comment on said issue with what the Snap is, its desktop file and actual WM_CLASS string from xprop, etc.

**Closed by JoshStrobl** 2017-10-22 15:32 UTC
