### ISSUE TITLE
New Workspace Switcher applet usability issue

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#1065] opened 2017-07-24 00:57 UTC
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1-404-g128a50a

Because of the "+" button we now have some sliding effect on the Panel. I think it is rather distracting and confusing. Check this out. User wants to select the 1 Workspace which is slides away:

![Alt Text](http://i.imgur.com/vDCixPj.gif)

**Comment by fossfreedom** [comment] 2017-07-24 08:10
duplicate of this https://github.com/budgie-desktop/budgie-desktop/issues/1017

**Closed by fossfreedom** 2017-07-24 08:10 UTC
Labels: duplicate
